DATA = [('Alcatel OT 813D','http://www.infibeam.com/Mobiles/i-Alcatel-OT-813D-Dual-SIM/P-E-M-Alcatel-OT-813D.html'),
('Apple iPhone 3GS 8GB','http://www.infibeam.com/Mobiles/i-Apple-iPhone-3GS-8GB/P-E-M-Apple-iPhone-3GS-8GB.html'),
('BlackBerry 9330','http://www.infibeam.com/Mobiles/i-BlackBerry-3G-9330-SmartPhone/P-E-M-BlackBerry-9330.html'),
('BlackBerry 9800 Torch','http://www.infibeam.com/Mobiles/i-BlackBerry-Torch-9800-OS6-Smartphone/P-E-M-BlackBerry-9800-Torch.html'),
('BlackBerry Bold 9790','http://www.infibeam.com/Mobiles/i-BlackBerry-Bold-9790-SmartPhone/P-E-M-BlackBerry-Bold-9790.html'),
('BlackBerry Bold Touch 9900','http://www.infibeam.com/Mobiles/i-BlackBerry-Bold-Touch-9900-Smartphone/P-E-M-BlackBerry-Bold-Touch-9900.html'),
('BlackBerry Curve 8520','http://www.infibeam.com/Mobiles/i-BlackBerry-Curve-8520-SmartPhone/P-E-M-BlackBerry-Curve8520.html'),
('BlackBerry Curve 9360','http://www.infibeam.com/Mobiles/i-BlackBerry-Curve-9360-Android-Smartphone/P-E-M-BlackBerry-Curve-9360.html'),
('BlackBerry Curve 9380','http://www.infibeam.com/Mobiles/i-BlackBerry-Curve-9380-SmartPhone/P-E-M-BlackBerry-Curve-9380.html'),
('BlackBerry Style 9670','http://www.infibeam.com/Mobiles/i-BlackBerry-Style-9670-3G-Smartphone/P-E-M-BlackBerry-Style-9670.html'),
('BlackBerry Torch 9810','http://www.infibeam.com/Mobiles/i-BlackBerry-Torch-9810-3G-Smartphone/P-E-M-BlackBerry-Torch-9810.html'),
('BlackBerry Torch 9860','http://www.infibeam.com/Mobiles/i-BlackBerry-Torch-9860-Touchscreen-Smartphone/P-E-M-BlackBerry-Torch-9860.html'),
('Dell XCD28','http://www.infibeam.com/Mobiles/i-Dell-XCD28-3G-Android-Smartphone/P-E-M-Dell-XCD28.html'),
('Dell XCD35','http://www.infibeam.com/Mobiles/i-Dell-XCD35-Android-3G-Smartphone/P-E-M-Dell-XCD35.html'),
('HTC EVO 3D','http://www.infibeam.com/Mobiles/i-HTC-EVO-3D-Android-Smartphone/P-E-M-HTC-EVO-3D.html'),
('HTC Legend A6363','http://www.infibeam.com/Mobiles/i-HTC-Legend-A6363/P-E-M-HTC-Legend.html'),
('Intex IN 007 Maxima','http://www.infibeam.com/Mobiles/i-Intex-Maxima-Dual-Sim-Mobile/P-E-M-Intex-IN-007-Maxima.html'),
('Intex IN 1212 Nano Plus','http://www.infibeam.com/Mobiles/i-Intex-IN-1212-Nano-Plus/P-E-M-Intex-IN-1212-Nano-Plus.html'),
('Intex IN 2040E','http://www.infibeam.com/Mobiles/i-Intex-IN-2040-E-DualSIM/P-E-M-Intex-IN2040E.html'),
('Intex IN 2060','http://www.infibeam.com/Mobiles/i-Intex-IN-2060-Dual-SIM/P-E-M-Intex-2060.html'),
('Intex IN 2080','http://www.infibeam.com/Mobiles/i-Intex-IN-2080-Dual-Sim/P-E-M-Intex-IN2080.html'),
('Intex IN 5030','http://www.infibeam.com/Mobiles/i-Intex-IN-5030-Triple-SIM/P-E-M-Intex-IN5030.html'),
('Intex IN 8809 Projector','http://www.infibeam.com/Mobiles/i-Intex-IN-8009-Vshow-Projector/P-E-M-Intex-IN-8809-Projector.html'),
('Intex IN 8810 Projector','http://www.infibeam.com/Mobiles/i-Intex-IN-8810-Projector-Mobile/P-E-M-Intex-IN8810-Projector.html'),
('Intex Kool 4370','http://www.infibeam.com/Mobiles/i-Intex-Kool-Dual-Sim-Mobile/P-E-M-Intex-Kool-4370.html'),
('Karbonn K 111','http://www.infibeam.com/Mobiles/i-Karbonn-K111-Dual-SIM-Multimedia/P-E-M-Karbonn-K111.html'),
('Karbonn K 505','http://www.infibeam.com/Mobiles/i-Karbonn-K505-Dual-SIM-Mobile/P-E-M-Karbonn-K505.html'),
('Karbonn K336','http://www.infibeam.com/Mobiles/i-Karbonn-K336-Dual-SIM-Multimedia/P-E-M-Karbonn-K336.html'),
('Karbonn K433','http://www.infibeam.com/Mobiles/i-Karbonn-K433-Dual-Sim/P-E-M-Karbonn-K433.html'),
('Karbonn K455','http://www.infibeam.com/Mobiles/i-Karbonn-K455-Dual-SIM-Slider/P-E-M-Karbonn-K455.html'),
('Karbonn K666','http://www.infibeam.com/Mobiles/i-Karbonn-K666-Dual-Sim/P-E-M-Karbonn-K666.html'),
('LG A120','http://www.infibeam.com/Mobiles/i-LG-A120-Dual-Speaker-Mobile/P-E-M-LG-A120.html'),
('LG A165','http://www.infibeam.com/Mobiles/i-LG-A165-Dual-SIM-Mobile/P-E-M-LG-A165.html'),
('LG A230','http://www.infibeam.com/Mobiles/i-LG-A230-Dual-SIM-Mobile/P-E-M-LG-A230.html'),
('LG BL40 New Chocolate','http://www.infibeam.com/Mobiles/i-LG-BL40-New-Chocolate-Smartphone/P-E-M-LG-BL40.html'),
('LG C105','http://www.infibeam.com/Mobiles/i-LG-C105-QWERTY-Smartphone/P-E-M-LG-C105.html'),
('LG Cookie Duet C310','http://www.infibeam.com/Mobiles/i-LG-Cookie-Duet-C310-Smartphone/P-E-M-LG-C310.html'),
('LG Cookie Fresh GS290','http://www.infibeam.com/Mobiles/i-LG-Cookie-Fresh-GS290-Smartphone/P-E-M-LG-GS290.html'),
('LG GB110 Bullet','http://www.infibeam.com/Mobiles/i-LG-GB110-Bullet/P-E-M-LG-GB110Bullet-Bullet.html'),
('LG GB220','http://www.infibeam.com/Mobiles/i-LG-GB220-Flip/P-E-M-LG-GB220.html'),
('LG GS108','http://www.infibeam.com/Mobiles/i-LG-GS108-Mobile-Phone/P-E-M-LG-GS108.html'),
('LG GS155','http://www.infibeam.com/Mobiles/i-LG-GS155-Mobile/P-E-M-LG-GS155.html'),
('LG GU220','http://www.infibeam.com/Mobiles/i-LG-GU220-Slider-Mobile/P-E-M-LG-GU220.html'),
('LG GU285','http://www.infibeam.com/Mobiles/i-LG-GU285-3G-Slider-Mobile/P-E-M-LG-GU285.html'),
('LG GW300','http://www.infibeam.com/Mobiles/i-LG-GW300/P-E-M-LG-GW300.html'),
('LG GX300','http://www.infibeam.com/Mobiles/i-LG-GX300-Dual-SIM-Mobile/P-E-M-LG-GX300.html'),
('LG GX500','http://www.infibeam.com/Mobiles/i-LG-GX500-Dual-SIM-Mobile/P-E-M-LG-GX500.html'),
('LG Optimus 2X P990','http://www.infibeam.com/Mobiles/i-LG-Optimus-2X-P990-Dualcore/P-E-M-LG-Optimus-2X-P990.html'),
('LG Optimus 3D P920','http://www.infibeam.com/Mobiles/i-LG-Optimus-3D-P920-Smartphone/P-E-M-LG-3D-P920.html'),
('LG Optimus Black P970','http://www.infibeam.com/Mobiles/i-LG-Optimus-Black-P970-Smartphone/P-E-M-LG-Optimus-Black-P970.html'),
('LG Optimus Hub E510','http://www.infibeam.com/Mobiles/i-LG-Optimus-Hub-E510-Smartphone/P-E-M-LG-E510.html'),
('LG Optimus Me P350','http://www.infibeam.com/Mobiles/i-LG-Optimus-Me-P350-Android/P-E-M-LG-Optimus-Me-P350.html'),
('LG Optimus NET P690','http://www.infibeam.com/Mobiles/i-LG-Optimus-NET-P690-SmartPhone/P-E-M-LG-Optimus-NET-P690.html'),
('LG Optimus One P500','http://www.infibeam.com/Mobiles/i-LG-Optimus-One-P500-Smartphone/P-E-M-LG-P500.html'),
('LG Optimus Pro C660','http://www.infibeam.com/Mobiles/i-LG-Optimus-ProC660-Qwerty-Phone/P-E-M-LG-Optimus-Pro-C660.html'),
('LG Optimus Sol E730','http://www.infibeam.com/Mobiles/i-LG-Smartphone-Optimus-Sol-E730/P-E-M-LG-Optimus-Sol-E730.html'),
('LG Optimus Sol E730','http://www.infibeam.com/Mobiles/i-LG-Optimus-Sol-E730-Android/P-E-M-LG-E730.html'),
('LG P520','http://www.infibeam.com/Mobiles/i-LG-P520-Dual-SIM-Touchscreen/P-E-M-LG-P520.html'),
('LG S310','http://www.infibeam.com/Mobiles/i-LG-S310-Mobile-Phone/P-E-M-LG-S310.html'),
('LG T300 Cookie Joy','http://www.infibeam.com/Mobiles/i-LG-T300-Cookie-Joy-Smartphone/P-E-M-LG-T300.html'),
('LG T515','http://www.infibeam.com/Mobiles/i-LG-T515-Touchscreen-Mobile/P-E-M-LG-T515.html'),
('LG X330','http://www.infibeam.com/Mobiles/i-LG-X330-Dual-SIM-Multimedia/P-E-M-LG-X330.html'),
('Lava A10','http://www.infibeam.com/Mobiles/i-Lava-A10-First-Touch-Screen/P-E-M-Lava-A10.html'),
('Lava A11 Dual Sim With Clamshell','http://www.infibeam.com/Mobiles/i-Lava-A11-Dual-Flip-Phone/P-E-M-Lava-A11.html'),
('Lava A16 MTV Phone','http://www.infibeam.com/Mobiles/i-Lava-A16-MTV-Dual-Phone/P-E-M-Lava-A16.html'),
('Lava B5 Qwerty','http://www.infibeam.com/Mobiles/i-Lava-B5-Qwerty-Smartphone-DualSim/P-E-M-Lava-B5Qwerty.html'),
('Lava B8 - Dual Sim','http://www.infibeam.com/Mobiles/i-Lava-B8-Dual-SIM-QWERTY/P-E-M-Lava-B8.html'),
('Lava KKT 30','http://www.infibeam.com/Mobiles/i-Lava-KKT-30-Dual-Sim/P-E-M-Lava-KKT30.html'),
('Lava M70','http://www.infibeam.com/Mobiles/i-Lava-M70-Dual-Sim-Smartphone/P-E-M-Lava-M70.html'),
('Lava M9','http://www.infibeam.com/Mobiles/i-Lava-M9-Dual-Sim-Mobile/P-E-M-Lava-M9.html'),
('Lava S12','http://www.infibeam.com/Mobiles/i-Lava-S12-Android-Mobile/P-E-M-Lava-S12.html'),
('Lemon Duo 212','http://www.infibeam.com/Mobiles/i-Lemon-Duo-212-Mobile-Phone/P-E-M-Lemon-Duo212.html'),
('Lemon Duo 306','http://www.infibeam.com/Mobiles/i-Lemon-Duo-306-Dual-SIM/P-E-M-Lemon-Duo-306.html'),
('Lemon Duo 309','http://www.infibeam.com/Mobiles/i-Lemon-Duo-309-GSM-Mobile/P-E-M-Lemon-Duo309.html'),
('Lemon Duo 325','http://www.infibeam.com/Mobiles/i-Lemon-Duo-325-Dual-SIM/P-E-M-Lemon-Duo325.html'),
('Lemon Duo 339 Super','http://www.infibeam.com/Mobiles/i-Lemon-Duo-339-Super-Mobile/P-E-M-Lemon-Duo-339-Super.html'),
('Lemon Duo 339','http://www.infibeam.com/Mobiles/i-Lemon-Duo-339-Mobile-Phone/P-E-M-Lemon-Duo339.html'),
('Lemon Duo 349','http://www.infibeam.com/Mobiles/i-Lemon-Duo-349-GSM-Mobile/P-E-M-Lemon-Duo349.html'),
('Lemon F101','http://www.infibeam.com/Mobiles/i-Lemon-F101-Flip-Mobile-Phone/P-E-M-Lemon-F101.html'),
('Lemon W100','http://www.infibeam.com/Mobiles/i-Lemon-W100-3G-Mobile-Phone/P-E-M-Lemon-W100.html'),
('Lemon iQ 505','http://www.infibeam.com/Mobiles/i-Lemon-iQ-505-Qwerty-Phone/P-E-M-Lemon-iQ505.html'),
('Maxx GC735','http://www.infibeam.com/Mobiles/i-Maxx-GC735-Dual-SIM-Slider/P-E-M-Maxx-GC735.html'),
('Maxx MQ601','http://www.infibeam.com/Mobiles/i-Maxx-MQ601-Dual-Sim-Mobile/P-E-M-Maxx-MQ601.html'),
('Maxx MSD7','http://www.infibeam.com/Mobiles/i-Maxx-MSD7-Dual-Sim-Mobile/P-E-M-Maxx-MSD7.html'),
('Maxx MT105','http://www.infibeam.com/Mobiles/i-Maxx-MT105-Zippy-Touchscreen-Phone/P-E-M-Maxx-MT105.html'),
('Maxx MX124','http://www.infibeam.com/Mobiles/i-Maxx-MX124-Dual-SIM-Mobile/P-E-M-Maxx-MX124.html'),
('Maxx MX166','http://www.infibeam.com/Mobiles/i-Maxx-MX166-Yoyo-Dualsim-Mobile/P-E-M-Maxx-MX166.html'),
('Maxx MX192','http://www.infibeam.com/Mobiles/i-Maxx-MX192-Tune-Dualsim-Mobile/P-E-M-Maxx-MX192.html'),
('Maxx MX250','http://www.infibeam.com/Mobiles/i-Maxx-MX250-Dual-SIM-Mobile/P-E-M-Maxx-MX250.html'),
('Maxx MX349','http://www.infibeam.com/Mobiles/i-Maxx-MX349-Jazz-Dualsim-Phone/P-E-M-Maxx-MX349.html'),
('Maxx MX365','http://www.infibeam.com/Mobiles/i-Maxx-MX365-Dual-Sim-Mobile/P-E-M-Maxx-MX365.html'),
('Maxx MX372','http://www.infibeam.com/Mobiles/i-Maxx-MX372-Tiny-Dualsim-Mobile/P-E-M-Maxx-MX372.html'),
('Maxx MX388','http://www.infibeam.com/Mobiles/i-Maxx-MX388-Glo-Dualsim-Phone/P-E-M-Maxx-MX388.html'),
('Maxx MX469','http://www.infibeam.com/Mobiles/i-Maxx-MX469-Dual-Sim-Phone/P-E-M-Maxx-MX469.html'),
('Micromax A70','http://www.infibeam.com/Mobiles/i-Micromax-A70-Android-Mobile-Phone/P-E-M-Micromax-A70.html'),
('Micromax A85 Superfone Dual Core Android Smartphone','http://www.infibeam.com/Mobiles/i-Micromax-A85-Android-Smartphone/P-E-M-Micromax-A85.html'),
('Micromax Andro A60','http://www.infibeam.com/Mobiles/i-Micromax-Andro-A60-Android-Smartphone/P-E-M-Micromax-A60.html'),
('Micromax G4 Gamolution','http://www.infibeam.com/Mobiles/i-Micromax-G4-Gamolution-Dual-Sim/P-E-M-Micromax-G4.html'),
('Micromax GC256','http://www.infibeam.com/Mobiles/i-Micromax-GC256-Dual-SIM-Mobile/P-E-M-Micromax-GC256.html'),
('Micromax GC360','http://www.infibeam.com/Mobiles/i-Micromax-GC360-Dual-SIM-Mobile/P-E-M-Micromax-GC360.html'),
('Micromax M2','http://www.infibeam.com/Mobiles/i-Micromax-M2-Dual-SIM-Mobile/P-E-M-Micromax-M2.html'),
('Micromax Q2','http://www.infibeam.com/Mobiles/i-Micromax-Q2-Ezpad/P-E-M-Micromax-Q2.html'),
('Micromax Q2+','http://www.infibeam.com/Mobiles/i-Micromax-Q2-Dual-Band-Bluetooth/P-E-M-Micromax-Q2Plus.html'),
('Micromax Q3 Plus Ezpad','http://www.infibeam.com/Mobiles/i-Micromax-Q3-Plus-EZPAD-Smartphone/P-E-M-Micromax-Q3-Plus-Ezpad.html'),
('Micromax Q35','http://www.infibeam.com/Mobiles/i-Micromax-Q35-Qwerty-Mobile-Phone/P-E-M-Micromax-Q35.html'),
('Micromax Q50','http://www.infibeam.com/Mobiles/i-micromax-Q50-Ezpad-Qwerty-Mobile/P-E-M-Micromax-Q50.html'),
('Micromax Q55 Bling - Dual Sim','http://www.infibeam.com/Mobiles/i-Micromax-Q55-Bling-Dual-Sim/P-E-M-Micromax-Q55Bling.html'),
('Micromax Q56','http://www.infibeam.com/Mobiles/i-Micromax-Q56-Slider-QWERTY-Mobile/P-E-M-Micromax-Q56.html'),
('Micromax Q6','http://www.infibeam.com/Mobiles/i-Micromax-Q6-Dual-Sim/P-E-M-Micromax-Q6.html'),
('Micromax Q7','http://www.infibeam.com/Mobiles/i-Micromax-Q7-Ezpad-Dual-Sim/P-E-M-Micromax-Q7.html'),
('Micromax Q75','http://www.infibeam.com/Mobiles/i-Micromax-Q75-Dual-SIM-Standby/P-E-M-Micromax-Q75.html'),
('Micromax Q80','http://www.infibeam.com/Mobiles/i-Micromax-Q80-Qwerty-Mobile-Phone/P-E-M-Micromax-Q80.html'),
('Micromax W900','http://www.infibeam.com/Mobiles/i-Micromax-W900-Touchscreen-Dual-Sim/P-E-M-Micromax-W900.html'),
('Micromax X100','http://www.infibeam.com/Mobiles/i-Micromax-X100/P-E-M-Micromax-X100.html'),
('Micromax X111','http://www.infibeam.com/Mobiles/i-Micromax-X111/P-E-M-Micromax-X111.html'),
('Micromax X117','http://www.infibeam.com/Mobiles/i-Micromax-X117-Dual-SIM-Phone/P-E-M-Micromax-X117.html'),
('Micromax X200','http://www.infibeam.com/Mobiles/i-Micromax-X200-Dual-Sim-Mobile/P-E-M-Micromax-X200.html'),
('Micromax X210','http://www.infibeam.com/Mobiles/i-Micromax-X210-Dual-Sim-Mobile/P-E-M-Micromax-X210.html'),
('Micromax X222','http://www.infibeam.com/Mobiles/i-Micromax-X222-Touch-Screen-Mobile/P-E-M-Micromax-X222.html'),
('Micromax X228','http://www.infibeam.com/Mobiles/i-Micromax-X228-Dual-SIM-Mobile/P-E-M-Micromax-X228.html'),
('Micromax X229','http://www.infibeam.com/Mobiles/i-Micromax-X229-Dual-Sim-Phone/P-E-M-Micromax-X229.html'),
('Micromax X230','http://www.infibeam.com/Mobiles/i-Micromax-X230-Dual-SIM-Rugged/P-E-M-Micromax-X230.html'),
('Micromax X231','http://www.infibeam.com/Mobiles/i-Micromax-X231-Dual-Sim-Phone/P-E-M-Micromax-X231.html'),
('Micromax X235 (Universal Remote)','http://www.infibeam.com/Mobiles/i-Micromax-X235-Universal-Remote/P-E-M-Micromax-X235.html'),
('Micromax X261','http://www.infibeam.com/Mobiles/i-Micromax-Dual-Sim-X261/P-E-M-Micromax-X261.html'),
('Micromax X263','http://www.infibeam.com/Mobiles/i-Micromax-X263-Dual-Sim-Phone/P-E-M-Micromax-X263.html'),
('Micromax X265','http://www.infibeam.com/Mobiles/i-Micromax-X265-Dual-SIM-Mobile/P-E-M-Micromax-X265.html'),
('Micromax X266','http://www.infibeam.com/Mobiles/i-Micromax-X266-Dual-SIM-Mobile/P-E-M-Micromax-X266.html'),
('Micromax X270','http://www.infibeam.com/Mobiles/i-Micromax-Dual-Sim-X270/P-E-M-Micromax-X270.html'),
('Micromax X285','http://www.infibeam.com/Mobiles/i-Micromax-X285-Dual-SIM-Mobile/P-E-M-Micromax-X285.html'),
('Micromax X288','http://www.infibeam.com/Mobiles/i-Micromax-X288-Dual-Sim-Phone/P-E-M-Micromax-X288.html'),
('Micromax X290','http://www.infibeam.com/Mobiles/i-Micromax-X290-Dual-SIM-Mobile/P-E-M-Micromax-X290.html'),
('Micromax X330','http://www.infibeam.com/Mobiles/i-Micromax-X330-Dual-Sim/P-E-M-Micromax-X330.html'),
('Micromax X360','http://www.infibeam.com/Mobiles/i-Micromax-X360-Dual-Sim/P-E-M-Micromax-X360.html'),
('Micromax X365','http://www.infibeam.com/Mobiles/i-Micromax-X365-Dual-SIM-Rugged/P-E-M-Micromax-X365.html'),
('Micromax X395','http://www.infibeam.com/Mobiles/i-Micromax-X395-Dual-SIM-Mobile/P-E-M-Micromax-X395.html'),
('Micromax X40','http://www.infibeam.com/Mobiles/i-Micromax-X40-Projector-Phone/P-E-M-Micromax-X40.html'),
('Micromax X410','http://www.infibeam.com/Mobiles/i-Micromax-X410-Dual-Sim-Mobile/P-E-M-Micromax-X410.html'),
('Micromax X450','http://www.infibeam.com/Mobiles/i-Micromax-X450-Dual-SIM-Mobile/P-E-M-Micromax-X450.html'),
('Micromax X505','http://www.infibeam.com/Mobiles/i-Micromax-X505-Psych-Touchscreen-Phone/P-E-M-Micromax-X505.html'),
('Micromax X55 Blade','http://www.infibeam.com/Mobiles/i-Dual-Sim-Micromax-X55/P-E-M-Micromax-X55-Blade.html'),
('Micromax X560 Qube','http://www.infibeam.com/Mobiles/i-Micromax-X560-Qube-Smartphone/P-E-M-Micromax-X560-Qube.html'),
('Micromax X600','http://www.infibeam.com/Mobiles/i-Micromax-X600-Dual-Sim/P-E-M-Micromax-X600.html'),
('Micromax X78','http://www.infibeam.com/Mobiles/i-Micromax-Dual-Sim-X78/P-E-M-Micromax-X78.html'),
('Motorola Brea EX119 - Dual Sim','http://www.infibeam.com/Mobiles/i-Motorola-Brea-EX119-Mobile-Phone/P-E-M-Motorola-Brea-EX119.html'),
('Motorola EX115','http://www.infibeam.com/Mobiles/i-Motorola-EX115-Dual-SIM-Phone/P-E-M-Motorola-EX115.html'),
('Motorola EX128','http://www.infibeam.com/Mobiles/i-Motorola-EX128-Dual-SIM-Mobile/P-E-M-Motorola-EX128.html'),
('Motorola Erin EX109','http://www.infibeam.com/Mobiles/i-Motorola-Erin-EX109-Dual-SIM/P-E-M-Motorola-Erin-EX109.html'),
('Motorola Moto WX260','http://www.infibeam.com/Mobiles/i-Motorola-Moto-WX260/P-E-M-Motorola-MOTO-WX260.html'),
('Motorola Moto WX290','http://www.infibeam.com/Mobiles/i-Motorola-Moto-WX290/P-E-M-Motorola-MOTO-WX290.html'),
('Motorola Quartz EX212','http://www.infibeam.com/Mobiles/i-Motorola-Quartz-EX212-Dual-SIM/P-E-M-Motorola-Quartz-EX212.html'),
('Motorola RAZR XT910','http://www.infibeam.com/Mobiles/i-Motorola-RAZR-XT910-Android-SmartPhone/P-E-M-Motorola-RAZR-XT910.html'),
('Motorola WX181','http://www.infibeam.com/Mobiles/i-Motorola-MOTOYUVA-WX181-Radio-Phone/P-E-M-Motorola-WX181.html'),
('Nokia 100','http://www.infibeam.com/Mobiles/i-Nokia-100-GSM-Mobile-Phone/P-E-M-Nokia-100.html'),
('Nokia 101','http://www.infibeam.com/Mobiles/i-Nokia-101-GSM-Mobile-Phone/P-E-M-Nokia-101.html'),
('Nokia 1280','http://www.infibeam.com/Mobiles/i-Nokia-1280/P-E-M-Nokia-1280.html'),
('Nokia 1508','http://www.infibeam.com/Mobiles/i-Nokia-1508i-Mobile-Phone/P-E-M-Nokia-1508.html'),
('Nokia 1616','http://www.infibeam.com/Mobiles/i-Nokia-1616/P-E-M-Nokia-1616.html'),
('Nokia 2700 Classic','http://www.infibeam.com/Mobiles/i-Nokia-2700-Classic/P-E-M-Nokia-2700-Classic.html'),
('Nokia 2730 Classic','http://www.infibeam.com/Mobiles/i-Nokia-2730-Classic/P-E-M-Nokia-2730-Classic.html'),
('Nokia 500','http://www.infibeam.com/Mobiles/i-Nokia-500-TouchScreen-3G-SmartPhone/P-E-M-Nokia-500.html'),
('Nokia 5233','http://www.infibeam.com/Mobiles/i-Nokia-5233-Touch-Screen-SmartPhone/P-E-M-Nokia-5233.html'),
('Nokia 700','http://www.infibeam.com/Mobiles/i-Nokia-700-3G-TouchScreen-Smartphone/P-E-M-Nokia-700.html'),
('Nokia 701','http://www.infibeam.com/Mobiles/i-Nokia-701-Symbian-Belle-Smartphone/P-E-M-Nokia-701.html'),
('Nokia 7020 ( 1 Year Manufacturer Warranty )','http://www.infibeam.com/Mobiles/i-Nokia-7020-Fold/P-E-M-Nokia-7020.html'),
('Nokia 7230','http://www.infibeam.com/Mobiles/i-Nokia-7230-Slide/P-E-M-Nokia-7230.html'),
('Nokia Asha 200','http://www.infibeam.com/Mobiles/i-Nokia-Asha-200-Smartphone/P-E-M-Nokia-Asha-200.html'),
('Nokia Asha 300','http://www.infibeam.com/Mobiles/i-Nokia-Asha-300-Touchscreen-Mobile/P-E-M-Nokia-Asha-300.html'),
('Nokia C1-01','http://www.infibeam.com/Mobiles/i-Nokia-C1-01/P-E-M-Nokia-C1-01.html'),
('Nokia C1-02','http://www.infibeam.com/Mobiles/i-Nokia-C1-02/P-E-M-Nokia-C1-02.html'),
('Nokia C2-00','http://www.infibeam.com/Mobiles/i-Nokia-C2-00-Dual-SIM/P-E-M-Nokia-C2-00.html'),
('Nokia C2-01','http://www.infibeam.com/Mobiles/i-Nokia-C2-01-3G-Mobile/P-E-M-Nokia-C2-01.html'),
('Nokia C2-02','http://www.infibeam.com/Mobiles/i-Nokia-C2-02-Touch-Screen/P-E-M-Nokia-C2-02.html'),
('Nokia C2-03','http://www.infibeam.com/Mobiles/i-Nokia-C2-03-Dual-SIM/P-E-M-Nokia-C2-03.html'),
('Nokia C2-06','http://www.infibeam.com/Mobiles/i-Nokia-C2-06-Mobile-Phone/P-E-M-Nokia-C2-06.html'),
('Nokia C5-03','http://www.infibeam.com/Mobiles/i-Nokia-C5-03-Touchscreen-Smartphone/P-E-M-Nokia-C5-03.html'),
('Nokia C5-05','http://www.infibeam.com/Mobiles/i-Nokia-C5-05-Smartphone/P-E-M-Nokia-C5-05.html'),
('Nokia C6-01','http://www.infibeam.com/Mobiles/i-Nokia-C6-01/P-E-M-Nokia-C6-01.html'),
('Nokia E5','http://www.infibeam.com/Mobiles/i-Nokia-E5-E-Series/P-E-M-Nokia-E5.html'),
('Nokia E6','http://www.infibeam.com/Mobiles/i-Nokia-E6-Touch-Screen-Smartphone/P-E-M-Nokia-E6.html'),
('Nokia E63','http://www.infibeam.com/Mobiles/i-Nokia-E63-E-Series-SmartPhone/P-E-M-Nokia-E63.html'),
('Nokia E7','http://www.infibeam.com/Mobiles/i-Nokia-E7/P-E-M-Nokia-E7.html'),
('Nokia Lumia 710','http://www.infibeam.com/Mobiles/i-Nokia-Lumia-710-Touchscreen-Mobile/P-E-M-Nokia-Lumia-710.html'),
('Nokia Lumia 800','http://www.infibeam.com/Mobiles/i-Nokia-Lumia-800-Touchscreen-Mobile/P-E-M-Nokia-Lumia-800.html'),
('Nokia X1-01','http://www.infibeam.com/Mobiles/i-Nokia-X1-01-Dual-SIM/P-E-M-Nokia-X1-01.html'),
('Nokia X2','http://www.infibeam.com/Mobiles/i-Nokia-X2/P-E-M-Nokia-X2.html'),
('Nokia X2-01','http://www.infibeam.com/Mobiles/i-Nokia-X2-01-QWERTY-Smartphone/P-E-M-Nokia-X2-01.html'),
('Nokia X2-02','http://www.infibeam.com/Mobiles/i-Nokia-X2-02-Dualsim-Mobile/P-E-M-Nokia-X2-02.html'),
('Nokia X3-02 Touch and Type','http://www.infibeam.com/Mobiles/i-Nokia-X3-02-Touch-Type/P-E-M-Nokia-X3-02.html'),
('Onida F099','http://www.infibeam.com/Mobiles/i-Onida-F099-Dual-Sim-Mobile/P-E-M-Onida-F099.html'),
('Onida F970','http://www.infibeam.com/Mobiles/i-Onida-F970-3G-Dual-Camera/P-E-M-Onida-F970.html'),
('Onida G145','http://www.infibeam.com/Mobiles/i-Onida-G145-Mobile/P-E-M-Onida-G145.html'),
('Onida G590F','http://www.infibeam.com/Mobiles/i-Onida-G590F-Mobile/P-E-M-Onida-G590F.html'),
('Onida G720','http://www.infibeam.com/Mobiles/i-Onida-G720/P-E-M-Onida-G720.html'),
('Onida G725','http://www.infibeam.com/Mobiles/i-Onida-G725-Mobile/P-E-M-Onida-G725.html'),
('Onida KYT005','http://www.infibeam.com/Mobiles/i-Onida-KYT005-Dual-Sim-Mobile/P-E-M-Onida-KYT005.html'),
('Onida KYT007','http://www.infibeam.com/Mobiles/i-Onida-KYT007-GSM-Mobile-Phone/P-E-M-Onida-KYT007.html'),
('Samsung B5722','http://www.infibeam.com/Mobiles/i-Samsung-B5722-Smartphone/P-E-M-Samsung-B5722.html'),
('Samsung C3010','http://www.infibeam.com/Mobiles/i-Samsung-C3010/P-E-M-Samsung-C3010.html'),
('Samsung C3011','http://www.infibeam.com/Mobiles/i-Samsung-C3011-VGA-Camera-Mobile/P-E-M-Samsung-C3011.html'),
('Samsung C3312 Duos','http://www.infibeam.com/Mobiles/i-Samsung-Champ-Deluxe-Duos-C3312/P-E-M-Samsung-C3312.html'),
('Samsung C3520','http://www.infibeam.com/Mobiles/i-Samsung-C3520-Flip-Phone/P-E-M-Samsung-C3520.html'),
('Samsung C3752','http://www.infibeam.com/Mobiles/i-Samsung-C3752-Slider-DualSim-Mobile/P-E-M-Samsung-C3752.html'),
('Samsung C5212','http://www.infibeam.com/Mobiles/i-Samsung-C5212-Duos-Dual-SIM/P-E-M-Samsung-C5212.html'),
('Samsung C6112','http://www.infibeam.com/Mobiles/i-Samsung-C6112-Slider-Dual-SIM/P-E-M-Samsung-C6112.html'),
('Samsung Champ 2 C3330','http://www.infibeam.com/Mobiles/i-Samsung-Champ-2-C3330/P-E-M-Samsung-Champ-2-C3330.html'),
('Samsung Champ S3770','http://www.infibeam.com/Mobiles/i-Samsung-Champ-S3770-Smartphone/P-E-M-Samsung-Champ-S3770.html'),
('Samsung Champ-Mega Cam C3303I','http://www.infibeam.com/Mobiles/i-Samsung-Champ-Mega-Cam-C3303i/P-E-M-Samsung-Champ-Mega-Cam-C3303I.html'),
('Samsung Corby Plus B3410','http://www.infibeam.com/Mobiles/i-Samsung-Corby-Plus-B3410-SmartPhone/P-E-M-Samsung-CorbyPlus-B3410.html'),
('Samsung Corby S3653','http://www.infibeam.com/Mobiles/i-Samsung-Corby-S3653-Touch-Screen/P-E-M-Samsung-CorbyS3653.html'),
('Samsung Corby TXT B3210','http://www.infibeam.com/Mobiles/i-Samsung-Corby-TXT-B3210-SmartPhone/P-E-M-Samsung-CorbyTXT-B3210.html'),
('Samsung E1100 Guru','http://www.infibeam.com/Mobiles/i-Samsung-E1100-Guru/P-E-M-Samsung-GuruE1100.html'),
('Samsung E2152','http://www.infibeam.com/Mobiles/i-Samsung-E2152-Dual-SIM-Mobile/P-E-M-Samsung-E2152.html'),
('Samsung Galaxy 3 I5801','http://www.infibeam.com/Mobiles/i-Samsung-I5801-Galaxy3-Android-Smartphone/P-E-M-Samsung-I5801.html'),
('Samsung Galaxy 5 I5503','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-5-I5503-Android/P-E-M-Samsung-I5503.html'),
('Samsung Galaxy Fit S5670','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Fit-S5670-Android/P-E-M-Samsung-Galaxy-Fit-S5670.html'),
('Samsung Galaxy Pop S5570','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Pop-S5570-Android/P-E-M-Samsung-GalaxyPopS5570.html'),
('Samsung Galaxy Pro B7510','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Pro-B7510-Android/P-E-M-Samsung-Galaxy-Pro-B7510.html'),
('Samsung Galaxy R I9103','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-R-Android-Smartphone/P-E-M-Samsung-Galaxy-R-I9103.html'),
('Samsung Galaxy S LCD I9003','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-S-LCD-I9003/P-E-M-Samsung-Galaxy-S-LCD-I9003.html'),
('Samsung Galaxy Tab P1000 + Leather cover','http://www.infibeam.com/Mobiles/i-Samsung-P1000-Galaxy-Tab-Smartphone/P-E-M-Samsung-Galaxy-Tab-P1000.html'),
('Samsung Galaxy Y S5360','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Y-S5360-Smartphone/P-E-M-Samsung-Galaxy-Y-S5360.html'),
('Samsung Guru B559','http://www.infibeam.com/Mobiles/i-Samsung-Guru-B559-Mobile-Phone/P-E-M-Samsung-Guru-B559.html'),
('Samsung Guru Muzik B519','http://www.infibeam.com/Mobiles/i-Samsung-Guru-Muzik-SCH-B519/P-E-M-Samsung-Guru-Muzik-B519.html'),
('Samsung Hero E2230','http://www.infibeam.com/Mobiles/i-Samsung-Hero-E2230/P-E-M-Samsung-E2230.html'),
('Samsung Hero E2232','http://www.infibeam.com/Mobiles/i-Samsung-Hero-E2232-Dual-SIM/P-E-M-Samsung-E2232.html'),
('Samsung Hero E3210','http://www.infibeam.com/Mobiles/i-Samsung-Hero-E3210-3G-Mobile/P-E-M-Samsung-E3210.html'),
('Samsung Hero E3213','http://www.infibeam.com/Mobiles/i-Samsung-Hero-E3213-3G-Mobile/P-E-M-Samsung-E3213.html'),
('Samsung MPOWER TXT M369','http://www.infibeam.com/Mobiles/i-Samsung-Mpower-TXT-M369-Mobile/P-E-M-Samsung-MPOWER-TXT-M369.html'),
('Samsung Metro C3560','http://www.infibeam.com/Mobiles/i-Samsung-Metro-C3560-Mobile-Phone/P-E-M-Samsung-Metro-C3560.html'),
('Samsung Metro DUOS C3322','http://www.infibeam.com/Mobiles/i-Samsung-Metro-DUOS-C3322-Mobile/P-E-M-Samsung-Metro-DUOS-C3322.html'),
('Samsung Omnia W I8350','http://www.infibeam.com/Mobiles/i-Samsung-Omnia-W-I8350-Mobile/P-E-M-Samsung-Omnia-W-I8350.html'),
('Samsung S3600','http://www.infibeam.com/Mobiles/i-Samsung-S3600-Metro-Flip-Mobile/P-E-M-Samsung-S3600Metro.html'),
('Samsung S5200','http://www.infibeam.com/Mobiles/i-Samsung-Metro-S5200-Slider/P-E-M-Samsung-S5200Metro.html'),
('Samsung S5610','http://www.infibeam.com/Mobiles/i-Samsung-S5610-3G-Mobile-Phone/P-E-M-Samsung-S5610.html'),
('Samsung S5620 Monte','http://www.infibeam.com/Mobiles/i-Samsung-S5620-Monte/P-E-M-Samsung-S5620Monte.html'),
('Samsung Star Duos B7722','http://www.infibeam.com/Mobiles/i-Samsung-Star-Duos-B7722-Smartphone/P-E-M-Samsung-B7722-Duos.html'),
('Samsung Star II S5263','http://www.infibeam.com/Mobiles/i-Samsung-Star-II-S5263-Smartphone/P-E-M-Samsung-Star-II-S5263.html'),
('Samsung Wave II S8530','http://www.infibeam.com/Mobiles/i-Samsung-S8530-Wave-II-Smartphone/P-E-M-Samsung-Wave-II-S8530.html'),
('Samsung Wave III S8600','http://www.infibeam.com/Mobiles/i-Samsung-Wave-III-S8600-Java/P-E-M-Samsung-S-8600-Wave-III.html'),
('Samsung Wave M S7250','http://www.infibeam.com/Mobiles/i-Samsung-Wave-M-S7250-Smartphone/P-E-M-Samsung-Wave-M-S7250.html'),
('Samsung Wave Y S5380','http://www.infibeam.com/Mobiles/i-Samsung-Wave-Y-S5380-Smartphone/P-E-M-Samsung-Wave-Y-S5380.html'),
('Sony Ericsson Xperia X10 mini Pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-X10-Mini/P-E-M-Sony-Ericsson-XperiaX10miniPro.html'),
('Sony Ericsson Xperia X10 mini','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-X10-Mini/P-E-M-Sony-Ericsson-XperiaX10mini.html'),
('Sony Ericsson Xperia X8','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-X8-Android/P-E-M-Sony-Ericsson-Xperia-X8.html'),
('Spice D-90','http://www.infibeam.com/Mobiles/i-Spice-D-90-Dual-SIM/P-E-M-Spice-D-90.html'),
('Spice G-6550','http://www.infibeam.com/Mobiles/i-Spice-G6550-3G-Mobile-Phone/P-E-M-Spice-G-6550.html'),
('Spice M-4250','http://www.infibeam.com/Mobiles/i-Spice-M-4250-Dual-SIM/P-E-M-Spice-M-4250.html'),
('Spice M-5056','http://www.infibeam.com/Mobiles/i-Spice-M5056-Dual-Sim-Mobile/P-E-M-Spice-M-5056.html'),
('Spice M-5100','http://www.infibeam.com/Mobiles/i-Spice-M-5100-Dual-SIM/P-E-M-Spice-M-5100.html'),
('Spice M-5180','http://www.infibeam.com/Mobiles/i-Spice-M-5180-Dual-SIM/P-E-M-Spice-M-5180.html'),
('Spice M-5262','http://www.infibeam.com/Mobiles/i-Spice-M-5262-Dual-SIM/P-E-M-Spice-M-5262.html'),
('Spice M-5350','http://www.infibeam.com/Mobiles/i-Spice-M-5350-Elite-Dual/P-E-M-Spice-M-5350.html'),
('Spice M-5445','http://www.infibeam.com/Mobiles/i-Spice-M-5445-Music-Mobile/P-E-M-Spice-M-5445.html'),
('Spice M-5454','http://www.infibeam.com/Mobiles/i-Spice-M-5454-Dual-SIM/P-E-M-Spice-M-5454.html'),
('Spice M-5570','http://www.infibeam.com/Mobiles/i-Spice-M-5570-Mobile-Phone/P-E-M-Spice-M-5570.html'),
('Spice M-5700 Flo','http://www.infibeam.com/Mobiles/i-Spice-M-5700-Flo-Social/P-E-M-Spice-M-5700Flo.html'),
('Spice M-6 Sports','http://www.infibeam.com/Mobiles/i-Spice-M6-Sports-Dual-SIM/P-E-M-Spice-M-6-Sports.html'),
('Spice M-6200','http://www.infibeam.com/Mobiles/i-Spice-M6200-Dual-Sim-Mobile/P-E-M-Spice-M-6200.html'),
('Spice M-6350','http://www.infibeam.com/Mobiles/i-Spice-M6350-Dual-Sim-Phone/P-E-M-Spice-M-6350.html'),
('Spice M-6400','http://www.infibeam.com/Mobiles/i-Spice-M-6400-Dual-SIM/P-E-M-Spice-M-6400.html'),
('Spice M-6450 Metal','http://www.infibeam.com/Mobiles/i-Spice-M6450-Metal-Dual-Sim/P-E-M-Spice-M-6450-Metal.html'),
('Spice M-6460','http://www.infibeam.com/Mobiles/i-Spice-M6460-Dual-Sim-Mobile/P-E-M-Spice-M-6460.html'),
('Spice M-6900 Knight','http://www.infibeam.com/Mobiles/i-Spice-M6900-Knight-Dual-SIM/P-E-M-Spice-M-6900-Knight.html'),
('Spice MI-280','http://www.infibeam.com/Mobiles/i-Spice-MI-280-Dual-SIM/P-E-M-Spice-MI-280.html'),
('Spice Mi-270','http://www.infibeam.com/Mobiles/i-Spice-Mi270-Touchscreen-Android-Mobile/P-E-M-Spice-Mi-270.html'),
('Spice Mi-310','http://www.infibeam.com/Mobiles/i-Spice-Mi-310-Android-Smartphone/P-E-M-Spice-Mi-310.html'),
('Spice Popkorn M-9000 Projector','http://www.infibeam.com/Mobiles/i-Spice-M9000-Popkorn-Projector-Mobile/P-E-M-Spice-Popkorn-M-9000.html'),
('Videocon Qruz3 V1435','http://www.infibeam.com/Mobiles/i-Videocon-Qruz-3-V1435-Mobile/P-E-M-Videocon-V1435.html'),
('Videocon V1307 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1307-Dual-Sim-Phone/P-E-M-Videocon-V1307.html'),
('Videocon V1402','http://www.infibeam.com/Mobiles/i-Videocon-V1402-Dual-SIM/P-E-M-Videocon-V1402.html'),
('Videocon V1410','http://www.infibeam.com/Mobiles/i-Videocon-V1410-Dual-SIM-Mobile/P-E-M-Videocon-V1410.html'),
('Videocon V1412','http://www.infibeam.com/Mobiles/i-Videocon-V1412-Dual-SIM-Mobile/P-E-M-Videocon-V1412.html'),
('Videocon V1414 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1414-Dual-Sim/P-E-M-Videocon-V1414.html'),
('Videocon V1436','http://www.infibeam.com/Mobiles/i-Videocon-V1436-GSM-Mobile-Phone/P-E-M-Videocon-V1436.html'),
('Videocon V1440','http://www.infibeam.com/Mobiles/i-Videocon-V1440-Dual-Sim-Phone/P-E-M-Videocon-V1440.html'),
('Videocon V1448 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1448-Dual-Sim/P-E-M-Videocon-V1448.html'),
('Videocon V1450','http://www.infibeam.com/Mobiles/i-Videocon-V1450-Dual-SIM-Mobile/P-E-M-Videocon-V1450.html'),
('Videocon V1456 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1456-Dual-Sim/P-E-M-Videocon-V1456.html'),
('Videocon V1476','http://www.infibeam.com/Mobiles/i-Videocon-V1476-Dual-Sim-Mobile/P-E-M-Videocon-V1476.html'),
('Videocon V1530','http://www.infibeam.com/Mobiles/i-Videocon-V1530-Dual-SIM-Phone/P-E-M-Videocon-V1530.html'),
('Videocon V1531 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1531-Dual-Sim-Bar/P-E-M-Videocon-V1531.html'),
('Videocon V1533 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1533-Dual-Sim/P-E-M-Videocon-V1533.html'),
('Videocon V1540 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1540-Dual-Sim-Phone/P-E-M-Videocon-V1540.html'),
('Videocon V1606 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1606-GSM-Dual-Sim/P-E-M-Videocon-V1606.html'),
('Videocon V1611','http://www.infibeam.com/Mobiles/i-Videocon-V1611-Dual-Sim-Phone/P-E-M-Videocon-V1611.html'),
('Videocon V1688','http://www.infibeam.com/Mobiles/i-Videocon-V1688-Qwerty-Dual-SIM/P-E-M-Videocon-V1688.html'),
('Videocon V1705','http://www.infibeam.com/Mobiles/i-Videocon-V1705-Dual-SIM-Mobile/P-E-M-Videocon-V1705.html'),
('Videocon V1755','http://www.infibeam.com/Mobiles/i-Videocon-V1755-Touchscreen-Android/P-E-M-Videocon-V1755.html'),
('Videocon V1760','http://www.infibeam.com/Mobiles/i-Videocon-V1760-TouchScreen-Mobile-Phone/P-E-M-Videocon-V1760.html'),
('Videocon V202','http://www.infibeam.com/Mobiles/i-Videocon-V202-Mobile/P-E-M-Videocon-V202.html'),
('Videocon V7400','http://www.infibeam.com/Mobiles/i-Videocon-V7400-Android-Smartphone/P-E-M-Videocon-V7400.html'),
('Vodafone 858 Smart U8160','http://www.infibeam.com/Mobiles/i-Vodafone-Android-858-Smart-U8160/P-E-M-Vodafone-U8160.html'),
('Wynncom Y10','http://www.infibeam.com/Mobiles/i-Wynncom-Y10-Dual-Sim/P-E-M-Wynncom-Y10.html'),
('Wynncom Y30','http://www.infibeam.com/Mobiles/i-Wynncom-Y30-Dual-Sim-Mobile/P-E-M-Wynncom-Y30.html'),
('Wynncom Y50','http://www.infibeam.com/Mobiles/i-Wynncom-Y50-Dual-Sim/P-E-M-Wynncom-Y50.html'),
('Zen X410','http://www.infibeam.com/Mobiles/i-Zen-X410-Dual-Sim-Mobile/P-E-M-Zen-X410.html'),
('iBall Aura V36','http://www.infibeam.com/Mobiles/i-iBall-Aura-V36-Mobile-Phone/P-E-M-iBall-Aura-V36.html'),
('Intex IN 4470N+','http://www.infibeam.com/Mobiles/i-Intex-IN-4470N-Mobile-Phone/P-E-M-Intex-IN4470N.html'),
('iBall Aspire QE-45','http://www.infibeam.com/Mobiles/i-iBall-Aspire-QE45-Dual-SIM/P-E-M-iBall-Aspire-QE-45.html'),
('Micromax Q55 Bling-Black (Limited IIFA Edition)','http://www.infibeam.com/Mobiles/i-Micromax-Q55-Bling-Slider-DualSim/P-E-M-Micromax-Q55Bling-Black.html'),
('Alcatel OT 517D','http://www.infibeam.com/Mobiles/i-Alcatel-OT-517D-Dual-SIM/P-E-M-Alcatel-OT-517D.html'),
('Lemon Duo 216','http://www.infibeam.com/Mobiles/i-Lemon-Duo-216-Dual-SIM/P-E-M-Lemon-Duo216.html'),
('Samsung Mpower Muzik F219','http://www.infibeam.com/Mobiles/i-Samsung-Mpower-Muzik-SCH-F219/P-E-M-Samsung-Mpower-Muzik-F219.html'),
('iBall Shann S306','http://www.infibeam.com/Mobiles/i-iball-Shann-S306-Dual-SIM/P-E-M-iBall-S306.html'),
('Samsung Corby Pro B5310','http://www.infibeam.com/Mobiles/i-Samsung-Corby-Pro-B5310-SmartPhone/P-E-M-Samsung-CorbyPro-B5310.html'),
('Spice G6500','http://www.infibeam.com/Mobiles/i-Spice-G6500/P-E-M-Spice-G6500.html'),
('Spice M5370','http://www.infibeam.com/Mobiles/i-Spice-M5370-Dual-SIM-Phone/P-E-M-Spice-M5370.html'),
('Spice M6700','http://www.infibeam.com/Mobiles/i-Spice-M6700-Touch-Screen-Mobile/P-E-M-Spice-M6700.html'),
('Spice QT44 ( 1 Year Manufacturer Warranty )','http://www.infibeam.com/Mobiles/i-Spice-QT-44-Dual-Sim/P-E-M-Spice-QT44.html'),
('Spice QT52','http://www.infibeam.com/Mobiles/i-Spice-QT52-Dual-Sim/P-E-M-Spice-QT52.html'),
('Spice QT56','http://www.infibeam.com/Mobiles/i-Spice-QT56-DualSim-CDMA-GSM/P-E-M-Spice-QT56.html'),
('LG Optimus P698 Net Dual(Titanium)','http://www.infibeam.com/Mobiles/i-LG-Optimus-Dual-Sim-Android/P-E-M-LG-P698.html'),
('Lava KKT 34 Plus','http://www.infibeam.com/Mobiles/i-Lava-KKT-34-Plus-Dual/P-E-M-Lava-KKT34Plus.html'),
('Karbonn K210','http://www.infibeam.com/Mobiles/i-Karbonn-K210-Dual-Sim-Mobile/P-E-M-Karbonn-K210.html'),
('Karbonn K220','http://www.infibeam.com/Mobiles/i-Karbonn-K220-Dual-Sim-Phone/P-E-M-Karbonn-K220.html'),
('Karbonn K325','http://www.infibeam.com/Mobiles/i-Karbonn-K325-Dual-SIM-Mobile/P-E-M-Karbonn-K325.html'),
('Karbonn K334','http://www.infibeam.com/Mobiles/i-Karbonn-K334-Dual-Sim-Mobile/P-E-M-Karbonn-K334.html'),
('Karbonn K570','http://www.infibeam.com/Mobiles/i-Karbonn-K570-Dual-Sim/P-E-M-Karbonn-K570.html'),
('Samsung-Star S5233','http://www.infibeam.com/Mobiles/i-Samsung-Star-S5233-SmartPhone/P-E-M-Samsung-S5233-Star.html'),
('Onida F930-3G','http://www.infibeam.com/Mobiles/i-Onida-F930-3G-Mobile/P-E-M-Onida-F930-3G.html'),
('Onida G721-3G','http://www.infibeam.com/Mobiles/i-Onida-G721-Dual-Sim-Mobile/P-E-M-Onida-G721-3G.html'),
('LG- GM200','http://www.infibeam.com/Mobiles/i-LG-GM200/P-E-M-LG-GM200.html'),
('Samsung Chat 527','http://www.infibeam.com/Mobiles/i-Samsung-Champ-Chat-527-3G/P-E-M-Samsung-Champ-Chat-527.html'),
('Lava ARC21','http://www.infibeam.com/Mobiles/i-Lava-ARC21-Dual-Sim-Mobile/P-E-M-Lava-ARC21.html'),
('Lava KKT28','http://www.infibeam.com/Mobiles/i-Lava-KKT28-Dual-Sim-Phone/P-E-M-Lava-KKT28.html'),
('Lava KKT35','http://www.infibeam.com/Mobiles/i-Lava-KKT35-Dual-SIM-Phone/P-E-M-Lava-KKT35.html'),
('Lava KKT39','http://www.infibeam.com/Mobiles/i-Lava-KKT39-Dual-Sim-Mobile/P-E-M-Lava-KKT39.html'),
('Lava KKT40','http://www.infibeam.com/Mobiles/i-Lava-KKT40-Dual-Sim-Phone/P-E-M-Lava-KKT40.html'),
('Lava KKT50','http://www.infibeam.com/Mobiles/i-Lava-KKT50-Dual-Sim-Mobile/P-E-M-Lava-KKT50.html'),
('Spice C5060','http://www.infibeam.com/Mobiles/i-Spice-C5060-CDMA/P-E-M-Spice-C5060.html'),
('Spice M4262','http://www.infibeam.com/Mobiles/i-Spice-M4262-Dual-SIM-Mobile/P-E-M-Spice-M4262.html'),
('Spice M5115','http://www.infibeam.com/Mobiles/i-Spice-M5115-Dual-SIM-Phone/P-E-M-Spice-M5115.html'),
('Samsung Mpower TV S239','http://www.infibeam.com/Mobiles/i-Samsung-Mpower-TV-S239-Mobile/P-E-M-Samsung-Mpower-TV-S239.html'),
('iBall Shaan S09','http://www.infibeam.com/Mobiles/i-iBall-Shann-S09-Mobile-Phone/P-E-M-iBall-S09.html'),
('Karbonn A1','http://www.infibeam.com/Mobiles/i-Karbonn-A1-Touchscreen-Android-Mobile/P-E-M-Karbonn-A1.html'),
('Karbonn K1010','http://www.infibeam.com/Mobiles/i-Karbonn-K1010-TouchScreen-Dual-SIM/P-E-M-Karbonn-K1010.html'),
('Karbonn K1515','http://www.infibeam.com/Mobiles/i-Karbonn-K1515-TouchScreen-Dual-Sim/P-E-M-Karbonn-K1515.html'),
('Karbonn K1616','http://www.infibeam.com/Mobiles/i-Karbonn-K1616-TouchScreen-Mobile-Phone/P-E-M-Karbonn-K1616.html'),
('Karbonn K9','http://www.infibeam.com/Mobiles/i-Karbonn-K9-Dual-Sim-Phone/P-E-M-Karbonn-K9.html'),
('Apple iPhone 3GS-8GB Unlock','http://www.infibeam.com/Mobiles/i-Apple-iPhone-3Gs-Smartphone/P-E-M-Apple-iPhone-3GS-Unlock.html'),
('Alcatel OT 808','http://www.infibeam.com/Mobiles/i-Alcatel-OT-808-Smartphone/P-E-M-Alcatel-OT808.html'),
('Karbonn KC555','http://www.infibeam.com/Mobiles/i-Karbonn-KC555-Dual-SIM/P-E-M-Karbonn-KC555.html'),
('Lava M20','http://www.infibeam.com/Mobiles/i-Lava-M20-Dual-SIM-Mobile/P-E-M-Lava-M20.html'),
('LG GD580 (Cookie Flip)','http://www.infibeam.com/Mobiles/i-LG-Cookie-Flip-GD580/P-E-M-LG-GD580CookieFlip.html'),
('Samsung C3200 Monte Bar','http://www.infibeam.com/Mobiles/i-Samsung-C3200-Monte-Bar-Slider/P-E-M-Samsung-C3200.html'),
('Spice AURA (QT-64)','http://www.infibeam.com/Mobiles/i-Spice-Blueberry-Aura-QT64/P-E-M-Spice-AURAQT-64.html'),
('VOX-VPS-309','http://www.infibeam.com/Mobiles/i-VOX-VPS-309-Touch-Screen/P-E-M-VOX-VPS-309.html'),
('VOX- VES-105','http://www.infibeam.com/Mobiles/i-VOX-VES-105-Dual-Sim/P-E-M-VOX-VES-105.html'),
('Sony-Ericsson W8 Walkman Phone','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-W8-Android-Smartphone/P-E-M-Sony-Ericsson-W8-Walkman-Phone.html'),
('Sony-Ericsson W8 Walkman Phone','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-W8-Android-Smartphone/P-E-M-Sony-Ericsson-W8-Walkman-Phone-Combo.html'),
('Intex IN 4570 Xplode','http://www.infibeam.com/Mobiles/i-Intex-IN-4570-Xplode-Dualsim/P-E-M-Intex-IN-4570-Xplode.html'),
('Fujezone A200 Android Mobile','http://www.infibeam.com/Mobiles/i-Fujezone-A200-Android-Smartphone/P-E-M-Fujezone-A200.html'),
('Samsung Guru E1081T','http://www.infibeam.com/Mobiles/i-Samsung-Guru-E1081T-Mobile-Phone/P-E-M-Samsung-E1081T.html'),
('Samsung C3303K','http://www.infibeam.com/Mobiles/i-Samsung-Champ-C3303K-Touchscreen-Phone/P-E-M-Samsung-C3303K.html'),
('Samsung Metro 5200','http://www.infibeam.com/Mobiles/i-Samsung-Metro-5200-Slider/P-E-M-Samsung-Metro5200.html'),
('Onida Full Touch Mobile F101','http://www.infibeam.com/Mobiles/i-Onida-F101-Dual-Sim-Mobile/P-E-M-Onida-F101.html'),
('Intex IN 4070 Shine','http://www.infibeam.com/Mobiles/i-Intex-Shine-Dual-Sim-Mobile/P-E-M-Intex-IN-4070-Shine.html'),
('VOX- VGS-507','http://www.infibeam.com/Mobiles/i-VOX-VGS-507-Dual-Sim/P-E-M-VOX-VGS-507.html'),
('VOX- VGS-509','http://www.infibeam.com/Mobiles/i-VOX-VGS-509-Touch-Screen/P-E-M-VOX-VGS-509.html'),
('VOX- VGS-601','http://www.infibeam.com/Mobiles/i-VOX-VGS-601-Touch-Screen/P-E-M-VOX-VGS-601.html'),
('VOX- VGS-603','http://www.infibeam.com/Mobiles/i-VOX-VGS-603-Touch-Screen/P-E-M-VOX-VGS-603.html'),
('VOX- VPS-303','http://www.infibeam.com/Mobiles/i-VOX-VPS-303-SmartPhone/P-E-M-VOX-VPS-303.html'),
('VOX- VPS-305','http://www.infibeam.com/Mobiles/i-VOX-VPS-305-SmartPhone/P-E-M-VOX-VPS-305.html'),
('IBall Planet 3G (Special Choco)','http://www.infibeam.com/Mobiles/i-iBall-Planet-3G-Mobile-Phone/P-E-M-iBall-Planet-3G.html'),
('Karbonn K 550i','http://www.infibeam.com/Mobiles/i-Karbonn-K550i-Dual-SIM-Mobile/P-E-M-Karbonn-K550i.html'),
('Samsung E1160','http://www.infibeam.com/Mobiles/i-Samsung-E1160/P-E-M-Samsung-E1160.html'),
('Samsung E1225','http://www.infibeam.com/Mobiles/i-Samsung-E1225-Dual-Sim-Shift/P-E-M-Samsung-E1225.html'),
('Samsung Galaxy Y Color Plus S5360','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Y-Plus-S5360/P-E-M-Samsung-Galaxy-Y-Color-Plus-S5360.html'),
('Samsung I9000 Galaxy S','http://www.infibeam.com/Mobiles/i-samsung-I9000-Galaxy-S/P-E-M-Samsung-I9000.html'),
('Samsung S3310','http://www.infibeam.com/Mobiles/i-Samsung-Metro-S3310/P-E-M-Samsung-S3310-Metro.html'),
('Videocon V1635 (Black)','http://www.infibeam.com/Mobiles/i-Videocon-V1635-Dual-Sim/P-E-M-Videocon-V1635.html'),
('Onida KYT003','http://www.infibeam.com/Mobiles/i-Onida-KYT003-Dual-SIM-Mobile/P-E-M-Onida-KYT003.html'),
('LG GT350i','http://www.infibeam.com/Mobiles/i-LG-GT350i-Cookie-Glide-Smartphone/P-E-M-LG-GT350i.html'),
('Samsung E1175','http://www.infibeam.com/Mobiles/i-Samsung-E1175/P-E-M-Samsung-E1175T.html'),
('Samsung E1232 Hero Music (Black)','http://www.infibeam.com/Mobiles/i-Samsung-E1232-Mobile-Phones/P-E-M-Samsung-E1232-Hero-Music.html'),
('Alcatel OT 806D','http://www.infibeam.com/Mobiles/i-Alcatel-OT-806D-Mobile-Phone/P-E-M-Alcatel-OT-806D.html'),
('Lemon DUO 409','http://www.infibeam.com/Mobiles/i-Lemon-DUO409-Dual-Sim-Mobile/P-E-M-Lemon-DUO-409.html'),
('BlackBerry 9300 Curve','http://www.infibeam.com/Mobiles/i-BlackBerry-Curve-9300-3G-Smartphone/P-E-M-BlackBerry-9300-Curve.html'),
('BlackBerry Bold 3 9780','http://www.infibeam.com/Mobiles/i-BlackBerry-Bold-3-9780-Smartphone/P-E-M-BlackBerry-Bold-3-9780.html'),
('Karbonn K406 Boom Box','http://www.infibeam.com/Mobiles/i-Karbonn-K406-Dual-SIM-Music/P-E-M-Karbonn-K406.html'),
('LG A155','http://www.infibeam.com/Mobiles/i-LG-A155-Dual-SIM-Mobile/P-E-M-LG-A155.html'),
('Onida F090 Sparsh','http://www.infibeam.com/Mobiles/i-Onida-F090-Dual-Sim-Mobile/P-E-M-Onida-F090.html'),
('Maxx MX245','http://www.infibeam.com/Mobiles/i-Maxx-MX245-Trance-Dualsim-Phone/P-E-M-Maxx-MX245.html'),
('Samsung E1172','http://www.infibeam.com/Mobiles/i-Samsung-E1172-Dual-Sim-Phone/P-E-M-Samsung-E1172.html'),
('Videocon V1293','http://www.infibeam.com/Mobiles/i-Videocon-V1293-Dual-SIM-Mobile/P-E-M-Videocon-V1293.html'),
('Videocon V1545 (White)','http://www.infibeam.com/Mobiles/i-Videocon-V1545-Touchscreen-Mobile/P-E-M-Videocon-V1545.html'),
('Lava KKT22 Plus','http://www.infibeam.com/Mobiles/i-Lava-KKT22-Plus-Dual-SIM/P-E-M-Lava-KKT22-Plus.html'),
('Lava ARC01','http://www.infibeam.com/Mobiles/i-Lava-ARC01-Dual-SIM-Music/P-E-M-Lava-ARC01.html'),
('Maxx MX148','http://www.infibeam.com/Mobiles/i-Maxx-MX148-Arc-Dualsim-Mobile/P-E-M-Maxx-MX148.html'),
('Maxx MX434','http://www.infibeam.com/Mobiles/i-Maxx-MX434-Supremo-Dualsim-Mobile/P-E-M-Maxx-MX434.html'),
('Blackberry 9300 Curve','http://www.infibeam.com/Mobiles/i-BlackBerry-Curve-9300-3G-Smartphone/P-E-M-Blackberry-9300Curve.html'),
('Maxx MT250','http://www.infibeam.com/Mobiles/i-Maxx-MT250-Touch-Screen-Mobile/P-E-M-Maxx-MT250.html'),
('Alcatel OT 710D','http://www.infibeam.com/Mobiles/i-Alcatel-OT-710D-Mobile-Phone/P-E-M-Alcatel-OT-710D.html'),
('Onida V130','http://www.infibeam.com/Mobiles/i-Onida-V130-Dual-SIM/P-E-M-Onida-V130.html'),
('Micromax A 75','http://www.infibeam.com/Mobiles/i-Micromax-A75-SmartPhone/P-E-M-Micromax-A-75.html'),
('Onida G515','http://www.infibeam.com/Mobiles/i-Onida-G515-Dual-SIM-Phone/P-E-M-Onida-G515.html'),
('Spice QT-57','http://www.infibeam.com/Mobiles/i-Spice-QT-57/P-E-M-Spice-QT-57.html'),
('Lava KKT 24 Plus','http://www.infibeam.com/Mobiles/i-Lava-KKT-24-Plus-DualSim/P-E-M-Lava-KKT24Plus.html'),
('Lava KKT 24','http://www.infibeam.com/Mobiles/i-Lava-KKT-24-Dual-Sim/P-E-M-Lava-KKT24.html'),
('Karbonn K450','http://www.infibeam.com/Mobiles/i-Karbonn-K450-Dual-LCD/P-E-M-Karbonn-K450.html'),
('Karbonn K486','http://www.infibeam.com/Mobiles/i-Karbonn-K486-Dual-Sim-Mobile/P-E-M-Karbonn-K486.html'),
('Onida G480','http://www.infibeam.com/Mobiles/i-Onida-G480/P-E-M-Onida-G480.html'),
('Micromax X370','http://www.infibeam.com/Mobiles/i-Micromax-X370-Dual-SIM-Sleek/P-E-M-Micromax-X370.html'),
('Onida F810','http://www.infibeam.com/Mobiles/i-Onida-F810-Dual-SIM-Phone/P-E-M-Onida-F810.html'),
('Samsung B539','http://www.infibeam.com/Mobiles/i-Samsung-B539-3G-Mobile-Phone/P-E-M-Samsung-B539.html'),
('Samsung Duos W169','http://www.infibeam.com/Mobiles/i-Samsung-Duos-W169-Dual-SIM/P-E-M-Samsung-Duos-W169.html'),
('Samsung W259','http://www.infibeam.com/Mobiles/i-Samsung-W259-Duos-Dual-SIM/P-E-M-Samsung-W259.html'),
('Onida G695','http://www.infibeam.com/Mobiles/i-Onida-G695-Dual-Sim-Mobile/P-E-M-Onida-G695.html'),
('Samsung MpowerTxt M369','http://www.infibeam.com/Mobiles/i-Samsung-Mpower-Txt-CDMA-M369/P-E-M-Samsung-M369.html'),
('Orion E101','http://www.infibeam.com/Mobiles/i-Orion-E101-Dual-SIM-Mobile/P-E-M-Orion-E101.html'),
('LG 6400','http://www.infibeam.com/Mobiles/i-LG-6400-OMH-CDMA-Mobile/P-E-M-LG-6400.html'),
('Samsung Wave 575 S5753 + 2GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Samsung-Wave-575-S5753-Smartphone/P-E-M-Samsung-Wave-575-S5753.html'),
('Intex IN 4500 Thunder','http://www.infibeam.com/Mobiles/i-Intex-IN-4500-Thunder-Dualsim/P-E-M-Intex-IN-4500-Thunder.html'),
('Spice M-4580n','http://www.infibeam.com/Mobiles/i-Spice-M-4580n/P-E-M-Spice-M-4580n.html'),
('Samsung E2652 Champ Duos','http://www.infibeam.com/Mobiles/i-Samsung-E2652-Champ-Duos-Mobile/P-E-M-Samsung-E2652-Champ-Duos.html'),
('Samsung E1252','http://www.infibeam.com/Mobiles/i-Samsung-E1252-Dual-SIM-Mobile/P-E-M-Samsung-E1252.html'),
('Samsung S3850 Corby II','http://www.infibeam.com/Mobiles/i-Samsung-S3850-Corby-II-Phone/P-E-M-Samsung-S3850-Corby-II.html'),
('Samsung Corby Colours S3653IK','http://www.infibeam.com/Mobiles/i-Samsung-Corby-Colours-S3653IK/P-E-M-Samsung-S3653IK-Corby.html'),
('Alcatel OT 520D','http://www.infibeam.com/Mobiles/i-Alcatel-OT-520D-Mobile-Phone/P-E-M-Alcatel-OT-520D.html'),
('Intex IN 4666 Noise Proof','http://www.infibeam.com/Mobiles/i-Intex-IN-4666-Noise-Proof/P-E-M-Intex-IN-4666-Noise-Proof.html'),
('VOX-VGS-701','http://www.infibeam.com/Mobiles/i-VOX-VGS-701-Dual-Sim/P-E-M-VOX-VGS-701.html'),
('Lemon Duo 321','http://www.infibeam.com/Mobiles/i-Lemon-Duo-321-Dual-SIM/P-E-M-Lemon-Duo321.html'),
('Samsung Galaxy S Plus GT-I9001','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-S-Plus-i9001/P-E-M-Samsung-GT-I9001.html'),
('Samsung Chat 335 S3353 + 2GB Memory Card Free','http://www.infibeam.com/Mobiles/i-samsung-Chat-335-S3353-Smartphone/P-E-M-Samsung-Chat-335-S3353.html'),
('Spice MI 350','http://www.infibeam.com/Mobiles/i-Spice-MI-350-Android-Smartphone/P-E-M-Spice-MI-350.html'),
('Samsung Wave S7233','http://www.infibeam.com/Mobiles/i-Samsung-Wave-S7233-Smartphone/P-E-M-Samsung-Wave-S7233.html'),
('Zen Z80','http://www.infibeam.com/Mobiles/i-Zen-Z80-QWERTY-Mobile-Phone/P-E-M-Zen-Z80.html'),
('VOX- VES-107','http://www.infibeam.com/Mobiles/i-VOX-VES-107-Dual-Sim/P-E-M-VOX-VES-107.html'),
('VOX- VES-109','http://www.infibeam.com/Mobiles/i-VOX-VES-109-Dual-Sim/P-E-M-VOX-VES-109.html'),
('Lava ARC04','http://www.infibeam.com/Mobiles/i-Lava-ARC04-Dual-SIM-Phone/P-E-M-Lava-ARC04.html'),
('Lava ARC05','http://www.infibeam.com/Mobiles/i-Lava-ARC05-Dual-Sim-Mobile/P-E-M-Lava-ARC05.html'),
('Maxx MQ811','http://www.infibeam.com/Mobiles/i-Maxx-MQ811-Dual-Sim-Phone/P-E-M-Maxx-MQ811.html'),
('Maxx MT255','http://www.infibeam.com/Mobiles/i-Maxx-MT255-Maestro-Touchscreen-Phone/P-E-M-Maxx-MT255.html'),
('Maxx MT315','http://www.infibeam.com/Mobiles/i-Maxx-MT315-Ace-Dualsim-Mobile/P-E-M-Maxx-MT315.html'),
('VOX- VGS-501','http://www.infibeam.com/Mobiles/i-VOX-VGS-501-Touch-Screen/P-E-M-VOX-VGS-501.html'),
('VOX- VGS-503','http://www.infibeam.com/Mobiles/i-VOX-VGS-503-Dual-Sim/P-E-M-VOX-VGS-503.html'),
('VOX- VGS-505','http://www.infibeam.com/Mobiles/i-VOX-VGS-505-Touch-Screen/P-E-M-VOX-VGS-505.html'),
('VOX- VGS-605','http://www.infibeam.com/Mobiles/i-VOX-VGS-605-Dual-Sim/P-E-M-VOX-VGS-605.html'),
('VOX- VGS-703','http://www.infibeam.com/Mobiles/i-VOX-VGS-703-Dual-Camera/P-E-M-VOX-VGS-703.html'),
('Maxx MA440','http://www.infibeam.com/Mobiles/i-Maxx-MA440-Android-Mobile-Phone/P-E-M-Maxx-MA440.html'),
('Lemon iQ 303','http://www.infibeam.com/Mobiles/i-Lemon-iQ-303-Qwerty-Mobile/P-E-M-Lemon-iQ303.html'),
('Lemon DUO 419','http://www.infibeam.com/Mobiles/i-Lemon-DUO419-Dual-Sim-Mobile/P-E-M-Lemon-DUO-419.html'),
('Samsung Galxy SII I9100G','http://www.infibeam.com/Mobiles/i-Samsung-I9100G-Galaxy-S-II/P-E-M-Samsung-SII-I9100G.html'),
('LG 6160','http://www.infibeam.com/Mobiles/i-LG-6160-CDMA-Mobile/P-E-M-LG-6160.html'),
('Micromax Q5','http://www.infibeam.com/Mobiles/i-Micromax-Q5-Ezpad-Dual-SIM/P-E-M-Micromax-Q5.html'),
('Nokia N8','http://www.infibeam.com/Mobiles/i-Nokia-N8-SmartPhone/P-E-M-Nokia-N8.html'),
('Apple iPhone 4S-16GB','http://www.infibeam.com/Mobiles/i-Apple-iPhone-4S-16GB-SmartPhone/P-E-M-Apple-iPhone-4S-16GB.html'),
('Apple iPhone 4S-32GB','http://www.infibeam.com/Mobiles/i-Apple-iPhone-4S-32GB-SmartPhone/P-E-M-Apple-iPhone-4S-32GB.html'),
('Apple iPhone 4 32 GB (Officially Unlocked)','http://www.infibeam.com/Mobiles/i-Apple-iPhone-4-32GB-Smartphone/P-E-M-Apple-iPhone-4-32GB.html'),
('Maxx MS830','http://www.infibeam.com/Mobiles/i-Maxx-MS830-Touch-Screen-Mobile/P-E-M-Maxx-MS830.html'),
('Onida S555','http://www.infibeam.com/Mobiles/i-Onida-S555-Dual-Sim-Mobile/P-E-M-Onida-S555.html'),
('Samsung Monte Slider GT-E2550','http://www.infibeam.com/Mobiles/i-Samsung-GT-E2550-Monte-Slider/P-E-M-Samsung-E2550.html'),
('VOX- VGS-705','http://www.infibeam.com/Mobiles/i-VOX-VGS-705-Slider/P-E-M-VOX-VGS-705.html'),
('Nokia C3 Touch and Type','http://www.infibeam.com/Mobiles/i-Nokia-C3-Touch-and-Type/P-E-M-Nokia-C3-Touch-and-Type.html'),
('Nokia C3','http://www.infibeam.com/Mobiles/i-Nokia-C3/P-E-M-Nokia-C3.html'),
('Nokia C5','http://www.infibeam.com/Mobiles/i-Nokia-C5/P-E-M-Nokia-C5.html'),
('Nokia C6','http://www.infibeam.com/Mobiles/i-Nokia-C6-Slider/P-E-M-Nokia-C6.html'),
('Nokia X7','http://www.infibeam.com/Mobiles/i-Nokia-X7-Touch-Screen-Smartphone/P-E-M-Nokia-X7.html'),
('Samsung E1085 GSM','http://www.infibeam.com/Mobiles/i-Samsung-E1085/P-E-M-Samsung-E1085.html'),
('VOX- VES-203- With Free Bluetooth','http://www.infibeam.com/Mobiles/i-VOX-VES-203-Dual-Sim/P-E-M-VOX-VES-203.html'),
('LG T310i + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-LG-T310i-Cookie-WiFi-Smartphone/P-E-M-LG-T310i.html'),
('Apple iPhone 4 16 GB (Officially Unlocked)','http://www.infibeam.com/Mobiles/i-Apple-iPhone-4-16GB-Smartphone/P-E-M-Apple-iPhone-4-16GB.html'),
('Lemon iT 414','http://www.infibeam.com/Mobiles/i-Lemon-iT-414-Dual-SIM/P-E-M-Lemon-iT-414.html'),
('Lava ARC 02 Plus','http://www.infibeam.com/Mobiles/i-Lava-ARC-02-Plus-DualSim/P-E-M-Lava-ARC02Plus.html'),
('Samsung C3530 Metro 3530','http://www.infibeam.com/Mobiles/i-Samsung-C3530-Metro-3530-Mobile/P-E-M-Samsung-C3530.html'),
('Lava ARC03 Plus','http://www.infibeam.com/Mobiles/i-Lava-ARC03-Plus-Dual-Sim/P-E-M-Lava-ARC03-Plus.html'),
('Lava B6 + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-Lava-B6-Dual-SIM-Camera/P-E-M-Lava-B6.html'),
('Dell Aero + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Dell-Aero-Android-Smartphone/P-E-M-Dell-Aero.html'),
('HTC ChaCha','http://www.infibeam.com/Mobiles/i-HTC-ChaCha-3G-Android-Smartphone/P-E-M-HTC-ChaCha.html'),
('HTC Desire HD','http://www.infibeam.com/Mobiles/i-HTC-Desire-HD-Android-Smartphone/P-E-M-HTC-Desire-HD.html'),
('HTC Desire S','http://www.infibeam.com/Mobiles/i-HTC-Desire-S-Android-SmartPhone/P-E-M-HTC-Desire-S.html'),
('HTC Desire Z','http://www.infibeam.com/Mobiles/i-HTC-Desire-Z-Android-Smartphone/P-E-M-HTC-Desire-Z.html'),
('HTC Desire','http://www.infibeam.com/Mobiles/i-HTC-Desire-3G-Android-Smartphone/P-E-M-HTC-Desire.html'),
('HTC Explorer 3.2 Inch Touch Screen (Royal Black)','http://www.infibeam.com/Mobiles/i-HTC-Explorer-Touch-Screen-Smartphone/P-E-M-HTC-Explorer.html'),
('HTC Incredible S + Free 8GB Memory Card','http://www.infibeam.com/Mobiles/i-HTC-Incredible-S-Android-Smartphone/P-E-M-HTC-IncredibleS.html'),
('HTC Rhyme','http://www.infibeam.com/Mobiles/i-HTC-Rhyme-Android-SmartPhone/P-E-M-HTC-Rhyme.html'),
('HTC Salsa C510e + Free 2GB MicroSD Card','http://www.infibeam.com/Mobiles/i-HTC-Salsa-C510e-Android-Smartphone/P-E-M-HTC-Salsa-C510e.html'),
('HTC Sensation XE with Beats Audio','http://www.infibeam.com/Mobiles/i-HTC-Sensation-XE-With-Audio/P-E-M-HTC-Sensation-XE.html'),
('HTC Sensation XL','http://www.infibeam.com/Mobiles/i-HTC-Sensation-XL-Mobile/P-E-M-HTC-Sensation-XL.html'),
('HTC Sensation','http://www.infibeam.com/Mobiles/i-HTC-Sensation-Android-Smartphone-Mobile/P-E-M-HTC-Sensation.html'),
('HTC Wildfire S + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-HTC-Wildfire-S-Android-Smartphone/P-E-M-HTC-Wildfire-S.html'),
('MTS Livewire SP 100 with MTS Locked','http://www.infibeam.com/Mobiles/i-MTS-Livewire-SP100-Android-Smartphone/P-E-M-MTS-Livewire-SP-100.html'),
('MTS Livewire ZTE N600','http://www.infibeam.com/Mobiles/i-MTS-Livewire-ZTEN600-Android-SmartPhone/P-E-M-MTS-ZTE-N600.html'),
('Micromax Bling 2','http://www.infibeam.com/Mobiles/i-Micromax-Bling2-Android-Dual-SIM/P-E-M-Micromax-Bling-2.html'),
('Micromax Q5c','http://www.infibeam.com/Mobiles/i-Micromax-Q5c-CDMA/P-E-M-Micromax-Q5c.html'),
('Micromax X11i','http://www.infibeam.com/Mobiles/i-Micromax-X11i-Dual-Sim-Mobile/P-E-M-Micromax-X11i.html'),
('Micromax X11i+','http://www.infibeam.com/Mobiles/i-Micromax-X11i-Plus-Dual-Sim/P-E-M-Micromax-X11i-Plus.html'),
('Micromax X1i','http://www.infibeam.com/Mobiles/i-Micromax-X1i-Dual-Sim/P-E-M-Micromax-X1i.html'),
('Micromax X2i','http://www.infibeam.com/Mobiles/i-Micromax-X2i-Dual-Sim/P-E-M-Micromax-X2i.html'),
('Micromax X2i+','http://www.infibeam.com/Mobiles/i-Micromax-X2i-Dual-Sim/P-E-M-Micromax-X2iPlus.html'),
('Motorola Backflip','http://www.infibeam.com/Mobiles/i-Motorola-Backflip-Android-Smartphone-MOTOBLUR/P-E-M-Motorola-Backflip.html'),
('Motorola Defy Plus','http://www.infibeam.com/Mobiles/i-Motorola-Defy-Plus-Android-SmartPhone/P-E-M-Motorola-Defy-Plus.html'),
('Motorola Defy','http://www.infibeam.com/Mobiles/i-Motorola-Defy-MOTOBLUR-Android-Smartphone/P-E-M-Motorola-Defy.html'),
('Motorola Flipout MOTOBLUR (With 2 GB Memory Card)','http://www.infibeam.com/Mobiles/i-Motorola-Flipout-MOTOBLUR-Android-Phone/P-E-M-Motorola-Flipout.html'),
('Motorola Milestone Tablet Xt720','http://www.infibeam.com/Mobiles/i-Motorola-Milestone-XT720-Android-Smartphone/P-E-M-Motorola-XT720.html'),
('Nokia 6303i classic','http://www.infibeam.com/Mobiles/i-Nokia-6303i-Classic/P-E-M-Nokia-6303iclassic.html'),
('Samsung Galaxy Note','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Note-Android-Tablet/P-E-M-Samsung-Galaxy-Note.html'),
('Samsung Galaxy Pop i559','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Pop-CDMA-i559/P-E-M-Samsung-Galaxy-Pop-i559.html'),
('Samsung Galaxy S Plus','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-S-Plus-Mobile/P-E-M-Samsung-Galaxy-S-Plus.html'),
('Samsung Nexus S','http://www.infibeam.com/Mobiles/i-Samsung-Nexus-S-Android-Smartphone/P-E-M-Samsung-Nexus-S.html'),
('Sony Ericsson Aino Classic Touchscreen Mobile','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Anio-Classic-Touchscreen/P-E-M-Sony-Ericsson-AinoClassic.html'),
('Sony Ericsson Cedar','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Cedar-GreenHeart-Mobile/P-E-M-Sony-Ericsson-Cedar.html'),
('Sony Ericsson Elm J10i2','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Elm-J10i2/P-E-M-Sony-Ericsson-ElmJ10i2.html'),
('Sony Ericsson Hazel','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Hazel-Slider/P-E-M-Sony-Ericsson-Hazel.html'),
('Sony Ericsson Live Walkman','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Live-With-Walkman/P-E-M-Sony-Ericsson-Live-Walkman.html'),
('Sony Ericsson Live Walkman','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Live-With-Walkman/P-E-M-Sony-Ericsson-Live-Walkman-Combo.html'),
('Sony Ericsson Mix Walkman WT13i','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Walkman-WT13i-SmartPhone/P-E-M-Sony-Ericsson-WT13i.html'),
('Sony Ericsson Mix Walkman','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Mix-Walkman-Touchscreen/P-E-M-Sony-Ericsson-Mix-Walkman-Combo.html'),
('Sony Ericsson Spiro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Spiro-Walkman-Phone/P-E-M-Sony-Ericsson-Spiro.html'),
('Sony Ericsson U5i Vivaz','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Vivaz-U5i-SmartPhone/P-E-M-Sony-Ericsson-VivazU5i.html'),
('Sony Ericsson Vivaz pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Vivaz-Pro-Touchscreen/P-E-M-Sony-Ericsson-Vivazpro.html'),
('Sony Ericsson Xperia Arc','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Arc-Smartphone/P-E-M-Sony-Ericsson-XperiaArc.html'),
('Sony Ericsson Xperia Play','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Play-Android/P-E-M-Sony-Ericsson-XperiaPlay.html'),
('Sony Ericsson Xperia Pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Pro-Smartphone/P-E-M-Sony-Ericsson-XperiaPro.html'),
('Sony Ericsson Xperia Pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Pro-Smartphone/P-E-M-Sony-Ericsson-XperiaPro-Combo.html'),
('Sony Ericsson Zylo','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Zylo-Walkman/P-E-M-Sony-Ericsson-Zylo.html'),
('Sony Ericsson txt','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-txt-Qwerty-SmartPhone/P-E-M-Sony-Ericsson-txt.html'),
('Spice Blueberry Express','http://www.infibeam.com/Mobiles/i-Spice-Blueberry-Express-Mobile-Phone/P-E-M-Spice-Blueberry-Express.html'),
('Spice Blueberry Mini','http://www.infibeam.com/Mobiles/i-Spice-Blueberry-Mini-Dual-SIM/P-E-M-Spice-Blueberry-Mini.html'),
('Spice Mi-350n','http://www.infibeam.com/Mobiles/i-Spice-Mi-350n-SmartPhone/P-E-M-Spice-Mi-350n.html'),
('iBall Flip Flipper','http://www.infibeam.com/Mobiles/i-iBall-Flip-Flipper-Dual-SIM/P-E-M-iBall-Flipper.html'),
('iBall Gracia','http://www.infibeam.com/Mobiles/i-iBall-Gracia-Dual-SIM-Mobile/P-E-M-iBall-Gracia.html'),
('iBall Posh Platina','http://www.infibeam.com/Mobiles/i-iBall-Posh-Platina-Dual-SIM/P-E-M-iBall-Platina.html'),
('iBall Senior Aasaan','http://www.infibeam.com/Mobiles/i-iBall-Senior-Aasaan-Mobile-Phone/P-E-M-iBall-Aasaan.html'),
('iBall Sleec Thin','http://www.infibeam.com/Mobiles/i-iBall-Sleec-Thin-Dual-SIM/P-E-M-iBall-Thin.html'),
('iBall Water Proof Floater','http://www.infibeam.com/Mobiles/i-iBall-Waterproof-Floater-Mobile-Phone/P-E-M-iBall-Floater.html'),
('Sony Ericsson Xperia Ray ST 18i','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Ray-ST18i/P-E-M-Sony-Ericsson-XperiaRayST18i.html'),
('Spice M-5500 TOUCH and TYPE Mobile','http://www.infibeam.com/Mobiles/i-Spice-M5500-Touch-Screen-Mobile/P-E-M-Spice-M-5500.html'),
('Sony Ericsson Xperia Active','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Active-Touchscreen/P-E-M-Sony-Ericsson-Xperia-Active-Combo.html'),
('Sony Ericsson Xperia Active','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Active-Touchscreen/P-E-M-Sony-Ericsson-Xperia-active.html'),
('Karbonn K25i','http://www.infibeam.com/Mobiles/i-Karbonn-K25-Dual-Sim/P-E-M-Karbonn-K25.html'),
('Sony-Ericsson Xperia Mini Pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Mini-Pro/P-E-M-Sony-Ericsson-Xeperia-Mini-Pro-Combo.html'),
('Sony-Ericsson Xperia Mini Pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Mini-Pro/P-E-M-Sony-Ericsson-Xeperia-Mini-Pro.html'),
('HTC WildFire','http://www.infibeam.com/Mobiles/i-HTC-WildFire-3G-Android-Smartphone/P-E-M-HTC-WildFire.html'),
('Micromax X226 + 1 GB Memory Card','http://www.infibeam.com/Mobiles/i-Micromax-X226-Dual-SIM-Music/P-E-M-Micromax-X226.html'),
('Samsung C3222 Chat 322','http://www.infibeam.com/Mobiles/i-Samsung-C3222-Chat-322-QWERTY/P-E-M-Samsung-C3222.html'),
('iBall Flip Glider','http://www.infibeam.com/Mobiles/i-iBall-Flip-Glider-Dual-SIM/P-E-M-iBall-Glider.html'),
('VOX- VPS-401- With Free Bluetooth','http://www.infibeam.com/Mobiles/i-VOX-VPS-401-Dual-Sim/P-E-M-VOX-VPS-401.html'),
('Sony Ericsson Xperia Neo V','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Neo-V/P-E-M-Sony-Ericsson-Xperia-Neo-V-Combo.html'),
('MTS MTag 3.1 SP-101 + Free Call Mate Bluetooth & Screen Guard','http://www.infibeam.com/Mobiles/i-MTS-MTag-3-1-SP/P-E-M-MTS-Mtag-31-SP-101.html'),
('Sony Ericsson Txt pro','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Txt-Pro-Mobile/P-E-M-Sony-Ericsson-txt-pro.html'),
('Sony Ericsson Xperia Neo','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Neo-Android/P-E-M-Sony-Ericsson-XperiaNeo.html'),
('Micromax-Q66','http://www.infibeam.com/Mobiles/i-Micromax-Q66-Eclipse-Dual-SIM/P-E-M-Micromax-Q66.html'),
('Samsung Galaxy Ace S5830 + 2 GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Samsung-Galaxy-Ace-S5830-Android/P-E-M-Samsung-Galaxy-Ace-S5830.html'),
('Sony Ericsson Xperia ARC S','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-ARC-S/P-E-M-Sony-Ericsson-Xperia-arc-S-Combo.html'),
('Sony Ericsson Xperia ARC S','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-ARC-S/P-E-M-Sony-Ericsson-Xperia-arc-S.html'),
('Karbonn K446 + 2GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Karbonn-K446-Dual-Sim/P-E-M-Karbonn-K446.html'),
('Maxx MX463 + 2GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Maxx-MX463-Dual-SIM/P-E-M-Maxx-MX463.html'),
('Motorola Zeppelin Lite Xt5 Xt502','http://www.infibeam.com/Mobiles/i-Motorola-Quench-Xt5-Zeppelin-Lite/P-E-M-Motorola-Zeppelin-Lite-Xt5-Xt502.html'),
('Samsung Corby POP C3510','http://www.infibeam.com/Mobiles/i-Samsung-Corby-POP-C3510-SmartPhone/P-E-M-Samsung-CorbyPOP-C3510.html'),
('Maxx MX317 + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Maxx-MX317-Dual-SIM-Candybar/P-E-M-Maxx-MX-317.html'),
('Swiss Sv45 Nice n Easy','http://www.infibeam.com/Mobiles/i-Swissvoice-Sv45-Dual-SIM-Mobile/P-E-M-Swiss-Sv45.html'),
('Samsung S5333 + 2GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Samsung-Wave-533-S5333-Smartphone/P-E-M-Samsung-S5333.html'),
('Sony-Ericsson Xperia Mini ST15i + 2 GB Card','http://www.infibeam.com/Mobiles/i-Sony-Ericsson-Xperia-Mini-ST15i/P-E-M-Sony-Ericsson-Xperia-Mini-ST15i.html'),
('Samsung Chat 222','http://www.infibeam.com/Mobiles/i-Samsung-Chat-222-Qwerty-Mobile/P-E-M-Samsung-Chat222.html'),
('iBall IPS-261 Price Touch and Type Mobile Phone','http://www.infibeam.com/Mobiles/i-iBall-Ips-Touch-Type-Mobile/P-E-M-iBall-IPS-261-touch.html'),
('Samsung Star-II-Duos-C6712','http://www.infibeam.com/Mobiles/i-Samsung-Star-Duos-C6712-Smartphone/P-E-M-Samsung-Star-II-Duos-C6712.html'),
('Motorola Fire + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Motorola-Fire-XT311-Android-Gingerbread/P-E-M-Motorola-Fire-XT311.html'),
('Motorola Fire XT + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Motorola-Fire-XT-Android-Gingerbread/P-E-M-Motorola-Fire-XT.html'),
('Micromax MODU T','http://www.infibeam.com/Mobiles/i-Modu-T-Lightest-Smartphone/P-E-M-Micromax-MODUT.html'),
('Spice S7000 GSM','http://www.infibeam.com/Mobiles/i-Spice-S7000/P-E-M-Spice-S7000.html'),
('iBall Andi','http://www.infibeam.com/Mobiles/i-iBall-Andi-Android-Smartphone/P-E-M-iBall-Andi.html'),
('iBall Long-B261 Shaan','http://www.infibeam.com/Mobiles/i-iBall-Long-B261-Shaan-Mobile/P-E-M-iBall-Long-B261.html'),
('HTC-Radar','http://www.infibeam.com/Mobiles/i-HTC-Radar-3G-TouchScreen-Smartphone/P-E-M-HTC-Radar.html'),
('Acer Liquid mini E310 + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Acer-Liquid-Mini-E310-Android/P-E-M-Acer-Liquid-mini-E310.html'),
('Samsung Hero-E2232 with Free Callmate emergency charger','http://www.infibeam.com/Mobiles/i-Samsung-Hero-E2232-Dual-SIM/P-E-M-Samsung-Combo1.html'),
('Motorola-Charm-MB502','http://www.infibeam.com/Mobiles/i-Motorola-Charm-MB502-Android-QWERTY/P-E-M-Motorola-Charm-MB502.html'),
('Samsung NX2 F699 + 1 GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Samsung-NX2-F699-Slider-Mobile/P-E-M-Samsung-NX2-F699.html'),
('LG T325 + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-LG-Cookie-Max-T325-Smartphone/P-E-M-LG-T325.html'),
('Motorola Droid Razer','http://www.infibeam.com/Mobiles/i-Motorola-Droid-Razer-Android-Smartphone/P-E-M-Motorola-Droid-Razer.html'),
('Micromax Q1-Plus with Camera','http://www.infibeam.com/Mobiles/i-Micromax-Q1-Plus-Dual-SIM/P-E-M-Micromax-Q1-Plus.html'),
('Motorola QUENCH XT3','http://www.infibeam.com/Mobiles/i-Motorola-Quench-XT3-Android-Smartphone/P-E-M-Motorola-QUENCHXT3.html'),
('LG LG235 + Inbuilt Photon','http://www.infibeam.com/Mobiles/i-LG-LG235-Mobile-Phone/P-E-M-LG-LG235.html'),
('Samsung Wave525-S5253','http://www.infibeam.com/Mobiles/i-Samsung-Wave-525-S5253/P-E-M-Samsung-Wave525-S5253.html'),
('Micromax X550 QUBE','http://www.infibeam.com/Mobiles/i-Micromax-X550-QUBE/P-E-M-Micromax-X550.html'),
('Acer beTouch E130 + 2 GB Memory Card Free','http://www.infibeam.com/Mobiles/i-Acer-beTouch-E130-3G-Smartphone/P-E-M-Acer-beTouch-E130.html'),
('Lemon Duo 402 + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-Lemon-Duo-402-Dual-SIM/P-E-M-Lemon-Duo402.html'),
('Swiss Sv75 One Touch + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Swiss-Sv75-One-Touch-Mobile/P-E-M-Swiss-Sv75.html'),
('Maxx MTP9','http://www.infibeam.com/Mobiles/i-Maxx-MTP9-Focus-Dualsim-Phone/P-E-M-Maxx-MTP9.html'),
('Lava C30 + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-Lava-C30-Slider-Mobile-Phone/P-E-M-Lava-C30.html'),
('Lava M30 + Free 2 GB Memory Card','http://www.infibeam.com/Mobiles/i-Lava-M30-Dual-SIM-Mobile/P-E-M-Lava-M30.html'),
('Videocon V1608 + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Videocon-V1608-Triple-SIM-Mobile/P-E-M-Videocon-V1608.html'),
('Onida I-9 Android','http://www.infibeam.com/Mobiles/i-Onida-I9-Android-Phone/P-E-M-Onida-I-9.html'),
('Acer beTouch-E210','http://www.infibeam.com/Mobiles/i-Acer-beTouch-E210-Android-Smartphone/P-E-M-Acer-beTouch-E210.html'),
('Swiss Sv65 Easy Messaging + Free 2 GB Card','http://www.infibeam.com/Mobiles/i-Swiss-Sv65-Easy-Messaging-Mobile/P-E-M-Swiss-Sv65.html'),
('VOX V1 Plus + Free Bluetooth & MP3','http://www.infibeam.com/Mobiles/i-VOX-V1-Plus-Mobile-Phone/P-E-M-VOX-V1-Plus.html'),
('Black Elemente 7 Inch 708 - 8GB 3G, Wifi, GPS Tablet','http://www.infibeam.com/Mobiles/i-Black-Elemente-Black-708-3G/P-E-M-Black-Elemente-Black-708-3G.html'),
('Swiss Sv25 Talk n Talk','http://www.infibeam.com/Mobiles/i-Swiss-Sv25-Talk-n-Talk/P-E-M-Swiss-Sv25.html'),
('VOX Multimedia Phone with camera & Bluetooth + Bluetooth + Mp3 Player','http://www.infibeam.com/Mobiles/i-VOX-Mobile-Bluetooth-Mp3-Player/P-E-M-VOX-V-1.html'),
('Wespro Zing Dual SIM Dual Battery Mobile -X5000i','http://www.infibeam.com/Mobiles/i-Wespro-Zing-X5000i-Dual-SIM/P-E-M-Wespro-ZingX5000i.html'),
('Fujezone VISION','http://www.infibeam.com/Mobiles/i-Fujezone-VISION-Dual-SIM/P-E-M-Fujezone-VISION.html'),
('Fly E 140','http://www.infibeam.com/Mobiles/i-Fly-E140-Touch-Screen-Mobile/P-E-M-Fly-E-140.html'),
('Fly E 146','http://www.infibeam.com/Mobiles/i-Fly-E-146-Touchscreen-Phone/P-E-M-Fly-E-146.html'),
('Intex IN 50 CDMA','http://www.infibeam.com/Mobiles/i-Intex-IN-50-CDMA/P-E-M-Intex-IN50.html'),
('Lava C51','http://www.infibeam.com/Mobiles/i-Lava-C51-Touch-Screen-Phone/P-E-M-Lava-C51.html'),
('Onida S333','http://www.infibeam.com/Mobiles/i-Onida-S333-Dual-SIM-Mobile/P-E-M-Onida-S333.html'),
('Vodafone Blue-VF555','http://www.infibeam.com/Mobiles/i-Vodafone-Blue-VF555-Mobile/P-E-M-Vodafone-Blue-VF555.html'),
('Lemon DUO IT 828','http://www.infibeam.com/Mobiles/i-Lemon-DUO-TouchScreen-GSM-Mobile/P-E-M-Lemon-DUO-IT-828.html'),
('Vox V1','http://www.infibeam.com/Mobiles/i-Vox-V1-Dual-Sim-Mobile/P-E-M-Vox-V1.html'),
('Lemon iQ 707','http://www.infibeam.com/Mobiles/i-Lemon-iQ-707-Dual-Sim/P-E-M-Lemon-iQ707.html'),
('VOX 307 Smart Phone + Free VOX V9 Mobile','http://www.infibeam.com/Mobiles/i-VOX-307-Smart-Phone-VOX/P-E-M-VOX-Combo.html'),
('VOX- VGS-701a','http://www.infibeam.com/Mobiles/i-VOX-VGS-701a-Dual-Camera/P-E-M-VOX-VGS-701a.html'),
('Fujezone C6 Android Mobile','http://www.infibeam.com/Mobiles/i-Fujezone-C6-Android-Smartphone/P-E-M-Fujezone-C6.html'),
('Fly B 405','http://www.infibeam.com/Mobiles/i-Fly-B-405-Qwerty-Smartphone/P-E-M-Fly-B-405.html'),
('VOX- VPS-307- With Free 2GB Card','http://www.infibeam.com/Mobiles/i-VOX-VPS-307-QWERTY-Keyboard/P-E-M-VOX-VPS-307.html'),
('Fly B450 Qwerty Mobile','http://www.infibeam.com/Mobiles/i-Fly-B450-Dual-SIM-QWERTY/P-E-M-Fly-B-450.html'),
('Wespro Zing Dual SIM Qwerty Mobile Phone-Q800','http://www.infibeam.com/Mobiles/i-Wespro-Zing-Q800-Dual-SIM/P-E-M-Wespro-ZingQ800.html'),
('Wespro Dual SIM Qwerty Mobile Phone-Q900','http://www.infibeam.com/Mobiles/i-Wespro-Q900-Dual-SIM-Qwerty/P-E-M-Wespro-Q900.html'),
('Fly MV 111','http://www.infibeam.com/Mobiles/i-Fly-MV-111-GSM-Mobile/P-E-M-Fly-MV-111.html'),
('Fly B 470','http://www.infibeam.com/Mobiles/i-Fly-B470-Dual-SIM-Mobile/P-E-M-Fly-B-470.html'),
('Accord A27','http://www.infibeam.com/Mobiles/i-Accord-A27-Dual-SIM-Mobile/P-E-M-Accord-A27.html'),
('Airfone AF-110','http://www.infibeam.com/Mobiles/i-Airfone-AF-110-Dual-SIM/P-E-M-Airfone-AF-110.html'),
('Fly B410 DS','http://www.infibeam.com/Mobiles/i-Fly-B410-DS-Qwerty-Smartphone/P-E-M-Fly-B410-DS.html'),
('Fly DS 114A','http://www.infibeam.com/Mobiles/i-Fly-DS-114A-Dual-SIM/P-E-M-Fly-DS-114A.html'),
('Fly DS 157','http://www.infibeam.com/Mobiles/i-Fly-DS-157-Champion-Dual/P-E-M-Fly-DS-157.html'),
('Fly DS 181','http://www.infibeam.com/Mobiles/i-Fly-DS-181-Dual-SIM/P-E-M-Fly-DS-181.html'),
('Fly GC 167','http://www.infibeam.com/Mobiles/i-Fly-GC-167-Mobile-Phone/P-E-M-Fly-GC-167.html'),
('Fly GC 222','http://www.infibeam.com/Mobiles/i-Fly-GC-222-Dual-SIM/P-E-M-Fly-GC-222.html'),
('Fly MC 125','http://www.infibeam.com/Mobiles/i-Fly-MC-125-Music-Phone/P-E-M-Fly-MC-125.html'),
('Fly MC 170','http://www.infibeam.com/Mobiles/i-Fly-MC-170-Dual-SIM/P-E-M-Fly-MC170.html'),
('Fly MV 115','http://www.infibeam.com/Mobiles/i-Fly-MV-115-Theatre-Mobile/P-E-M-Fly-MV-115.html'),
('Fly MV 120','http://www.infibeam.com/Mobiles/i-Fly-MV-120-Dual-SIM/P-E-M-Fly-MV-120.html'),
('Fly MV 124','http://www.infibeam.com/Mobiles/i-Fly-MV-124-Mobile-Phone/P-E-M-Fly-MV-124.html'),
('Fly MV 130','http://www.infibeam.com/Mobiles/i-Fly-MV-130-Theatre-Phone/P-E-M-Fly-MV-130.html'),
('Fly MV 135','http://www.infibeam.com/Mobiles/i-Fly-MV-135-Theatre-Phone/P-E-M-Fly-MV-135.html'),
('Fujezone AS E18+','http://www.infibeam.com/Mobiles/i-Fujezone-AS-E18-Dual-SIM/P-E-M-Fujezone-AS-E18-Plus.html'),
('Infibeam I5000','http://www.infibeam.com/Mobiles/i-Infibeam-I5000-QWERTY-Touch-Screen/P-E-M-Infibeam-I5000.html'),
('Infibeam I666','http://www.infibeam.com/Mobiles/i-Infibeam-I666-QWERTY-Dual-SIM/P-E-M-Infibeam-I666.html'),
('Olive Pad VT100','http://www.infibeam.com/Mobiles/i-Olive-Pad-VT100-Android-Tablet/P-E-M-Olive-VT100.html'),
('Olive V-G1100','http://www.infibeam.com/Mobiles/i-Olive-V-G1100/P-E-M-Olive-V-G1100.html'),
('Olive V-G2300','http://www.infibeam.com/Mobiles/i-Olive-VG2300-Multimedia-Mobile/P-E-M-Olive-V-G2300.html'),
('Olive V-G3000','http://www.infibeam.com/Mobiles/i-Olive-VG3000-Dual-SIM-Mobile/P-E-M-Olive-V-G3000.html'),
('Olive V-G800','http://www.infibeam.com/Mobiles/i-Olive-VG800-Dual-SIM-Smartphone/P-E-M-Olive-V-G800.html'),
('Olive V-G8000','http://www.infibeam.com/Mobiles/i-Olive-V-G8000/P-E-M-Olive-V-G8000.html'),
('Olive V-GC800','http://www.infibeam.com/Mobiles/i-Olive-Wiz-VGC800-Triple-SIM/P-E-M-Olive-V-GC800.html'),
('Orion 905','http://www.infibeam.com/Mobiles/i-Orion-905-Dual-SIM-QWERTY/P-E-M-Orion-905.html'),
('Orion 907','http://www.infibeam.com/Mobiles/i-Orion-907-Dual-SIM-QWERTY/P-E-M-Orion-907.html'),
('Orion 932','http://www.infibeam.com/Mobiles/i-Orion-932-Dual-SIM-Mobile/P-E-M-Orion-932.html'),
('Orion E201','http://www.infibeam.com/Mobiles/i-Orion-E201-Dual-SIM-Mobile/P-E-M-Orion-E201.html'),
('Orion E909','http://www.infibeam.com/Mobiles/i-Orion-E909-Dual-SIM-Mobile/P-E-M-Orion-E909.html'),
('Orion TV203','http://www.infibeam.com/Mobiles/i-Orion-TV203-Dual-SIM-Mobile/P-E-M-Orion-TV203.html'),
('Wespro WM1503','http://www.infibeam.com/Mobiles/i-Wespro-WM1503-Dual-SIM/P-E-M-Wespro-WM1503.html'),
('Wespro WM2107','http://www.infibeam.com/Mobiles/i-Wespro-WM2107-Dual-SIM/P-E-M-Wespro-WM2107.html'),
('Wespro WM3708i','http://www.infibeam.com/Mobiles/i-Wespro-WM3708i-Dual-SIM/P-E-M-Wespro-WM3708i.html')]